/* Generated by Yosys 0.57 (git sha1 3aca86049, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

module tt_um_felixfeierabend(ui_in, uo_out, uio_in, uio_out, uio_oe, ena, clk, rst_n);
  input [7:0] ui_in;
  wire [7:0] ui_in;
  output [7:0] uo_out;
  wire [7:0] uo_out;
  input [7:0] uio_in;
  wire [7:0] uio_in;
  output [7:0] uio_out;
  wire [7:0] uio_out;
  output [7:0] uio_oe;
  wire [7:0] uio_oe;
  input ena;
  wire ena;
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire clk_scaled;
  wire \clk_scaler.clk_val ;
  wire \clk_scaler.counter[0] ;
  wire \clk_scaler.counter[10] ;
  wire \clk_scaler.counter[11] ;
  wire \clk_scaler.counter[1] ;
  wire \clk_scaler.counter[2] ;
  wire \clk_scaler.counter[3] ;
  wire \clk_scaler.counter[4] ;
  wire \clk_scaler.counter[5] ;
  wire \clk_scaler.counter[6] ;
  wire \clk_scaler.counter[7] ;
  wire \clk_scaler.counter[8] ;
  wire \clk_scaler.counter[9] ;
  wire signal_bit;
  wire \signal_gen.periodA[0] ;
  wire \signal_gen.periodA[1] ;
  wire \signal_gen.periodA[2] ;
  wire \signal_gen.periodA[3] ;
  wire \signal_gen.periodA[4] ;
  wire \signal_gen.tonegenA.clk_val ;
  wire \signal_gen.tonegenA.counter[0] ;
  wire \signal_gen.tonegenA.counter[10] ;
  wire \signal_gen.tonegenA.counter[11] ;
  wire \signal_gen.tonegenA.counter[1] ;
  wire \signal_gen.tonegenA.counter[2] ;
  wire \signal_gen.tonegenA.counter[3] ;
  wire \signal_gen.tonegenA.counter[4] ;
  wire \signal_gen.tonegenA.counter[5] ;
  wire \signal_gen.tonegenA.counter[6] ;
  wire \signal_gen.tonegenA.counter[7] ;
  wire \signal_gen.tonegenA.counter[8] ;
  wire \signal_gen.tonegenA.counter[9] ;
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _086_ (
    .I(\clk_scaler.counter[4] ),
    .ZN(_068_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _087_ (
    .I(rst_n),
    .ZN(_069_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _088_ (
    .I(\signal_gen.tonegenA.counter[7] ),
    .ZN(_070_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _089_ (
    .I(\signal_gen.tonegenA.counter[4] ),
    .ZN(_071_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _090_ (
    .I(\signal_gen.periodA[4] ),
    .ZN(_072_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _091_ (
    .I(\signal_gen.tonegenA.counter[5] ),
    .ZN(_073_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _092_ (
    .I(\signal_gen.periodA[3] ),
    .ZN(_074_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _093_ (
    .I(\signal_gen.tonegenA.counter[2] ),
    .ZN(_075_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _094_ (
    .I(\signal_gen.tonegenA.counter[1] ),
    .ZN(_076_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _095_ (
    .I(\signal_gen.tonegenA.counter[0] ),
    .ZN(_077_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _096_ (
    .I(\clk_scaler.clk_val ),
    .ZN(_001_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _097_ (
    .I(\signal_gen.tonegenA.clk_val ),
    .ZN(_003_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or3_1 _098_ (
    .A1(\clk_scaler.counter[1] ),
    .A2(\clk_scaler.counter[2] ),
    .A3(\clk_scaler.counter[3] ),
    .Z(_078_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _099_ (
    .A1(\clk_scaler.counter[5] ),
    .A2(\clk_scaler.counter[4] ),
    .A3(_078_),
    .ZN(_079_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _100_ (
    .A1(\clk_scaler.counter[10] ),
    .A2(\clk_scaler.counter[11] ),
    .ZN(_080_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor4_1 _101_ (
    .A1(\clk_scaler.counter[7] ),
    .A2(\clk_scaler.counter[6] ),
    .A3(\clk_scaler.counter[9] ),
    .A4(\clk_scaler.counter[8] ),
    .ZN(_081_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _102_ (
    .A1(_079_),
    .A2(_080_),
    .A3(_081_),
    .ZN(_082_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _103_ (
    .A1(ena),
    .A2(_082_),
    .ZN(_002_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai211_1 _104_ (
    .A1(_076_),
    .A2(\signal_gen.periodA[1] ),
    .B(\signal_gen.periodA[0] ),
    .C(_077_),
    .ZN(_083_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _105_ (
    .A1(_075_),
    .A2(\signal_gen.periodA[2] ),
    .B1(_076_),
    .B2(\signal_gen.periodA[1] ),
    .ZN(_084_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _106_ (
    .A1(_075_),
    .A2(\signal_gen.periodA[2] ),
    .ZN(_085_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi221_1 _107_ (
    .A1(\signal_gen.tonegenA.counter[3] ),
    .A2(_074_),
    .B1(_083_),
    .B2(_084_),
    .C(_085_),
    .ZN(_035_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _108_ (
    .A1(_071_),
    .A2(\signal_gen.periodA[4] ),
    .B(_073_),
    .ZN(_036_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _109_ (
    .A1(\signal_gen.tonegenA.counter[7] ),
    .A2(\signal_gen.tonegenA.counter[6] ),
    .Z(_037_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai221_1 _110_ (
    .A1(\signal_gen.tonegenA.counter[4] ),
    .A2(_072_),
    .B1(\signal_gen.tonegenA.counter[3] ),
    .B2(_074_),
    .C(_037_),
    .ZN(_038_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or2_1 _111_ (
    .A1(_036_),
    .A2(_038_),
    .Z(_039_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or4_1 _112_ (
    .A1(\signal_gen.tonegenA.counter[11] ),
    .A2(\signal_gen.tonegenA.counter[10] ),
    .A3(\signal_gen.tonegenA.counter[9] ),
    .A4(\signal_gen.tonegenA.counter[8] ),
    .Z(_040_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _113_ (
    .A1(_036_),
    .A2(_037_),
    .B(_040_),
    .ZN(_041_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _114_ (
    .A1(_035_),
    .A2(_039_),
    .B(_041_),
    .ZN(_000_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai211_1 _115_ (
    .A1(_035_),
    .A2(_039_),
    .B(_041_),
    .C(_069_),
    .ZN(_042_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _116_ (
    .A1(\signal_gen.tonegenA.counter[0] ),
    .A2(_042_),
    .ZN(_004_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _117_ (
    .A1(_076_),
    .A2(\signal_gen.tonegenA.counter[0] ),
    .Z(_043_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _118_ (
    .A1(_042_),
    .A2(_043_),
    .ZN(_005_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and3_1 _119_ (
    .A1(\signal_gen.tonegenA.counter[2] ),
    .A2(\signal_gen.tonegenA.counter[1] ),
    .A3(\signal_gen.tonegenA.counter[0] ),
    .Z(_044_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _120_ (
    .A1(\signal_gen.tonegenA.counter[1] ),
    .A2(\signal_gen.tonegenA.counter[0] ),
    .B(\signal_gen.tonegenA.counter[2] ),
    .ZN(_045_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _121_ (
    .A1(_042_),
    .A2(_044_),
    .A3(_045_),
    .ZN(_006_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xnor2_1 _122_ (
    .A1(\signal_gen.tonegenA.counter[3] ),
    .A2(_044_),
    .ZN(_046_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _123_ (
    .A1(_042_),
    .A2(_046_),
    .ZN(_007_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and3_1 _124_ (
    .A1(\signal_gen.tonegenA.counter[4] ),
    .A2(\signal_gen.tonegenA.counter[3] ),
    .A3(_044_),
    .Z(_047_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _125_ (
    .A1(\signal_gen.tonegenA.counter[3] ),
    .A2(_044_),
    .B(\signal_gen.tonegenA.counter[4] ),
    .ZN(_048_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _126_ (
    .A1(_042_),
    .A2(_047_),
    .A3(_048_),
    .ZN(_008_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _127_ (
    .A1(\signal_gen.tonegenA.counter[5] ),
    .A2(_047_),
    .ZN(_049_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _128_ (
    .A1(_073_),
    .A2(_047_),
    .Z(_050_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _129_ (
    .A1(_042_),
    .A2(_050_),
    .ZN(_009_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _130_ (
    .A1(\signal_gen.tonegenA.counter[6] ),
    .A2(\signal_gen.tonegenA.counter[5] ),
    .A3(_047_),
    .ZN(_051_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _131_ (
    .A1(\signal_gen.tonegenA.counter[6] ),
    .A2(_049_),
    .Z(_052_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _132_ (
    .A1(_042_),
    .A2(_052_),
    .ZN(_010_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _133_ (
    .A1(_070_),
    .A2(_051_),
    .B(_042_),
    .ZN(_011_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _134_ (
    .A1(_069_),
    .A2(_001_),
    .ZN(_016_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _135_ (
    .A1(rst_n),
    .A2(_003_),
    .ZN(_017_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _136_ (
    .A1(uio_in[1]),
    .A2(uio_in[0]),
    .A3(uio_in[2]),
    .ZN(_053_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _137_ (
    .A1(ui_in[0]),
    .A2(_053_),
    .ZN(_054_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _138_ (
    .I0(ui_in[3]),
    .I1(\signal_gen.periodA[0] ),
    .S(_054_),
    .Z(_018_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _139_ (
    .I0(ui_in[4]),
    .I1(\signal_gen.periodA[1] ),
    .S(_054_),
    .Z(_019_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _140_ (
    .I0(ui_in[5]),
    .I1(\signal_gen.periodA[2] ),
    .S(_054_),
    .Z(_020_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _141_ (
    .A1(ui_in[6]),
    .A2(_054_),
    .ZN(_055_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _142_ (
    .A1(_074_),
    .A2(_054_),
    .B(_055_),
    .ZN(_021_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _143_ (
    .A1(ui_in[7]),
    .A2(_054_),
    .ZN(_056_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _144_ (
    .A1(_072_),
    .A2(_054_),
    .B(_056_),
    .ZN(_022_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _145_ (
    .A1(ena),
    .A2(rst_n),
    .ZN(_057_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or2_1 _146_ (
    .A1(_082_),
    .A2(_057_),
    .Z(_058_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _147_ (
    .A1(\clk_scaler.counter[0] ),
    .A2(_058_),
    .ZN(_023_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _148_ (
    .A1(\clk_scaler.counter[0] ),
    .A2(\clk_scaler.counter[1] ),
    .ZN(_059_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xnor2_1 _149_ (
    .A1(\clk_scaler.counter[0] ),
    .A2(\clk_scaler.counter[1] ),
    .ZN(_060_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _150_ (
    .A1(_058_),
    .A2(_060_),
    .ZN(_024_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _151_ (
    .A1(\clk_scaler.counter[0] ),
    .A2(\clk_scaler.counter[1] ),
    .A3(\clk_scaler.counter[2] ),
    .ZN(_061_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _152_ (
    .A1(\clk_scaler.counter[2] ),
    .A2(_059_),
    .Z(_062_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _153_ (
    .A1(_058_),
    .A2(_062_),
    .ZN(_025_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand4_1 _154_ (
    .A1(\clk_scaler.counter[0] ),
    .A2(\clk_scaler.counter[1] ),
    .A3(\clk_scaler.counter[2] ),
    .A4(\clk_scaler.counter[3] ),
    .ZN(_063_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _155_ (
    .A1(\clk_scaler.counter[3] ),
    .A2(_061_),
    .Z(_064_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _156_ (
    .A1(_058_),
    .A2(_064_),
    .ZN(_026_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _157_ (
    .A1(_068_),
    .A2(_063_),
    .ZN(_065_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _158_ (
    .A1(\clk_scaler.counter[4] ),
    .A2(_063_),
    .Z(_066_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _159_ (
    .A1(_058_),
    .A2(_066_),
    .ZN(_027_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xnor2_1 _160_ (
    .A1(\clk_scaler.counter[5] ),
    .A2(_065_),
    .ZN(_067_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _161_ (
    .A1(_058_),
    .A2(_067_),
    .ZN(_028_)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _162_ (
    .CLK(clk_scaled),
    .D(_004_),
    .Q(\signal_gen.tonegenA.counter[0] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _163_ (
    .CLK(clk_scaled),
    .D(_005_),
    .Q(\signal_gen.tonegenA.counter[1] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _164_ (
    .CLK(clk_scaled),
    .D(_006_),
    .Q(\signal_gen.tonegenA.counter[2] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _165_ (
    .CLK(clk_scaled),
    .D(_007_),
    .Q(\signal_gen.tonegenA.counter[3] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _166_ (
    .CLK(clk_scaled),
    .D(_008_),
    .Q(\signal_gen.tonegenA.counter[4] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _167_ (
    .CLK(clk_scaled),
    .D(_009_),
    .Q(\signal_gen.tonegenA.counter[5] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _168_ (
    .CLK(clk_scaled),
    .D(_010_),
    .Q(\signal_gen.tonegenA.counter[6] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _169_ (
    .CLK(clk_scaled),
    .D(_011_),
    .Q(\signal_gen.tonegenA.counter[7] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _170_ (
    .CLK(clk_scaled),
    .D(_012_),
    .Q(\signal_gen.tonegenA.counter[8] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _171_ (
    .CLK(clk_scaled),
    .D(_013_),
    .Q(\signal_gen.tonegenA.counter[9] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _172_ (
    .CLK(clk_scaled),
    .D(_014_),
    .Q(\signal_gen.tonegenA.counter[10] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _173_ (
    .CLK(clk_scaled),
    .D(_015_),
    .Q(\signal_gen.tonegenA.counter[11] )
  );
  \$_DLATCH_N_  \clk_scaler.clk_val_reg  /* _174_ */ (
    .D(_001_),
    .E(_002_),
    .Q(\clk_scaler.clk_val )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _175_ (
    .CLK(clk),
    .D(_016_),
    .Q(clk_scaled)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _176_ (
    .CLK(clk_scaled),
    .D(_017_),
    .Q(signal_bit)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _177_ (
    .CLK(clk_scaled),
    .D(_018_),
    .Q(\signal_gen.periodA[0] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _178_ (
    .CLK(clk_scaled),
    .D(_019_),
    .Q(\signal_gen.periodA[1] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _179_ (
    .CLK(clk_scaled),
    .D(_020_),
    .Q(\signal_gen.periodA[2] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffsnq_1 _180_ (
    .CLK(clk_scaled),
    .D(_021_),
    .Q(\signal_gen.periodA[3] ),
    .SETN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _181_ (
    .CLK(clk_scaled),
    .D(_022_),
    .Q(\signal_gen.periodA[4] ),
    .RN(rst_n)
  );
  \$_DLATCH_P_  \signal_gen.tonegenA.clk_val_reg  /* _182_ */ (
    .D(_003_),
    .E(_000_),
    .Q(\signal_gen.tonegenA.clk_val )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _183_ (
    .CLK(clk),
    .D(_023_),
    .Q(\clk_scaler.counter[0] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _184_ (
    .CLK(clk),
    .D(_024_),
    .Q(\clk_scaler.counter[1] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _185_ (
    .CLK(clk),
    .D(_025_),
    .Q(\clk_scaler.counter[2] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _186_ (
    .CLK(clk),
    .D(_026_),
    .Q(\clk_scaler.counter[3] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _187_ (
    .CLK(clk),
    .D(_027_),
    .Q(\clk_scaler.counter[4] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _188_ (
    .CLK(clk),
    .D(_028_),
    .Q(\clk_scaler.counter[5] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _189_ (
    .CLK(clk),
    .D(_029_),
    .Q(\clk_scaler.counter[6] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _190_ (
    .CLK(clk),
    .D(_030_),
    .Q(\clk_scaler.counter[7] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _191_ (
    .CLK(clk),
    .D(_031_),
    .Q(\clk_scaler.counter[8] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _192_ (
    .CLK(clk),
    .D(_032_),
    .Q(\clk_scaler.counter[9] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _193_ (
    .CLK(clk),
    .D(_033_),
    .Q(\clk_scaler.counter[10] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _194_ (
    .CLK(clk),
    .D(_034_),
    .Q(\clk_scaler.counter[11] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tieh _195_ (
    .Z(uio_oe[0])
  );
  gf180mcu_fd_sc_mcu7t5v0__tieh _196_ (
    .Z(uio_oe[1])
  );
  gf180mcu_fd_sc_mcu7t5v0__tieh _197_ (
    .Z(uio_oe[2])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _198_ (
    .ZN(uio_oe[3])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _199_ (
    .ZN(uio_oe[4])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _200_ (
    .ZN(uio_oe[5])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _201_ (
    .ZN(uio_oe[6])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _202_ (
    .ZN(uio_oe[7])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _203_ (
    .ZN(uio_out[0])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _204_ (
    .ZN(uio_out[1])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _205_ (
    .ZN(uio_out[2])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _206_ (
    .ZN(uio_out[3])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _207_ (
    .ZN(uio_out[4])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _208_ (
    .ZN(uio_out[5])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _209_ (
    .ZN(uio_out[6])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _210_ (
    .ZN(uio_out[7])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _211_ (
    .ZN(uo_out[1])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _212_ (
    .ZN(uo_out[2])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _213_ (
    .ZN(uo_out[3])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _214_ (
    .ZN(uo_out[4])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _215_ (
    .ZN(uo_out[5])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _216_ (
    .ZN(uo_out[6])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _217_ (
    .ZN(uo_out[7])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _218_ (
    .ZN(_034_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _219_ (
    .ZN(_033_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _220_ (
    .ZN(_032_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _221_ (
    .ZN(_031_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _222_ (
    .ZN(_030_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _223_ (
    .ZN(_029_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _224_ (
    .ZN(_015_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _225_ (
    .ZN(_014_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _226_ (
    .ZN(_013_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _227_ (
    .ZN(_012_)
  );
  gf180mcu_fd_sc_mcu7t5v0__buf_1 _228_ (
    .I(signal_bit),
    .Z(uo_out[0])
  );
endmodule
