/* Generated by Yosys 0.57 (git sha1 3aca86049, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

module tt_um_felixfeierabend(ui_in, uo_out, uio_in, uio_out, uio_oe, ena, clk, rst_n);
  input [7:0] ui_in;
  wire [7:0] ui_in;
  output [7:0] uo_out;
  wire [7:0] uo_out;
  input [7:0] uio_in;
  wire [7:0] uio_in;
  output [7:0] uio_out;
  wire [7:0] uio_out;
  output [7:0] uio_oe;
  wire [7:0] uio_oe;
  input ena;
  wire ena;
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  wire _0000_;
  wire _0001_;
  wire _0002_;
  wire _0003_;
  wire _0004_;
  wire _0005_;
  wire _0006_;
  wire _0007_;
  wire _0008_;
  wire _0009_;
  wire _0010_;
  wire _0011_;
  wire _0012_;
  wire _0013_;
  wire _0014_;
  wire _0015_;
  wire _0016_;
  wire _0017_;
  wire _0018_;
  wire _0019_;
  wire _0020_;
  wire _0021_;
  wire _0022_;
  wire _0023_;
  wire _0024_;
  wire _0025_;
  wire _0026_;
  wire _0027_;
  wire _0028_;
  wire _0029_;
  wire _0030_;
  wire _0031_;
  wire _0032_;
  wire _0033_;
  wire _0034_;
  wire _0035_;
  wire _0036_;
  wire _0037_;
  wire _0038_;
  wire _0039_;
  wire _0040_;
  wire _0041_;
  wire _0042_;
  wire _0043_;
  wire _0044_;
  wire _0045_;
  wire _0046_;
  wire _0047_;
  wire _0048_;
  wire _0049_;
  wire _0050_;
  wire _0051_;
  wire _0052_;
  wire _0053_;
  wire _0054_;
  wire _0055_;
  wire _0056_;
  wire _0057_;
  wire _0058_;
  wire _0059_;
  wire _0060_;
  wire _0061_;
  wire _0062_;
  wire _0063_;
  wire _0064_;
  wire _0065_;
  wire _0066_;
  wire _0067_;
  wire _0068_;
  wire _0069_;
  wire _0070_;
  wire _0071_;
  wire _0072_;
  wire _0073_;
  wire _0074_;
  wire _0075_;
  wire _0076_;
  wire _0077_;
  wire _0078_;
  wire _0079_;
  wire _0080_;
  wire _0081_;
  wire _0082_;
  wire _0083_;
  wire _0084_;
  wire _0085_;
  wire _0086_;
  wire _0087_;
  wire _0088_;
  wire _0089_;
  wire _0090_;
  wire _0091_;
  wire _0092_;
  wire _0093_;
  wire _0094_;
  wire _0095_;
  wire _0096_;
  wire _0097_;
  wire _0098_;
  wire _0099_;
  wire _0100_;
  wire _0101_;
  wire _0102_;
  wire _0103_;
  wire _0104_;
  wire _0105_;
  wire _0106_;
  wire _0107_;
  wire _0108_;
  wire _0109_;
  wire _0110_;
  wire _0111_;
  wire _0112_;
  wire _0113_;
  wire _0114_;
  wire _0115_;
  wire _0116_;
  wire _0117_;
  wire _0118_;
  wire _0119_;
  wire _0120_;
  wire _0121_;
  wire _0122_;
  wire _0123_;
  wire _0124_;
  wire _0125_;
  wire _0126_;
  wire _0127_;
  wire _0128_;
  wire _0129_;
  wire _0130_;
  wire _0131_;
  wire _0132_;
  wire _0133_;
  wire _0134_;
  wire _0135_;
  wire _0136_;
  wire _0137_;
  wire _0138_;
  wire _0139_;
  wire _0140_;
  wire _0141_;
  wire _0142_;
  wire _0143_;
  wire _0144_;
  wire _0145_;
  wire _0146_;
  wire _0147_;
  wire _0148_;
  wire _0149_;
  wire _0150_;
  wire _0151_;
  wire _0152_;
  wire _0153_;
  wire _0154_;
  wire _0155_;
  wire _0156_;
  wire _0157_;
  wire _0158_;
  wire _0159_;
  wire _0160_;
  wire _0161_;
  wire _0162_;
  wire _0163_;
  wire _0164_;
  wire _0165_;
  wire _0166_;
  wire _0167_;
  wire _0168_;
  wire _0169_;
  wire _0170_;
  wire _0171_;
  wire _0172_;
  wire _0173_;
  wire _0174_;
  wire _0175_;
  wire _0176_;
  wire _0177_;
  wire _0178_;
  wire _0179_;
  wire _0180_;
  wire _0181_;
  wire _0182_;
  wire _0183_;
  wire _0184_;
  wire _0185_;
  wire _0186_;
  wire _0187_;
  wire _0188_;
  wire _0189_;
  wire _0190_;
  wire _0191_;
  wire _0192_;
  wire _0193_;
  wire _0194_;
  wire _0195_;
  wire _0196_;
  wire _0197_;
  wire _0198_;
  wire _0199_;
  wire _0200_;
  wire _0201_;
  wire _0202_;
  wire _0203_;
  wire _0204_;
  wire _0205_;
  wire _0206_;
  wire _0207_;
  wire _0208_;
  wire _0209_;
  wire _0210_;
  wire _0211_;
  wire _0212_;
  wire _0213_;
  wire _0214_;
  wire _0215_;
  wire _0216_;
  wire _0217_;
  wire _0218_;
  wire _0219_;
  wire _0220_;
  wire _0221_;
  wire _0222_;
  wire _0223_;
  wire _0224_;
  wire _0225_;
  wire _0226_;
  wire _0227_;
  wire _0228_;
  wire _0229_;
  wire _0230_;
  wire _0231_;
  wire _0232_;
  wire _0233_;
  wire _0234_;
  wire _0235_;
  wire _0236_;
  wire _0237_;
  wire _0238_;
  wire _0239_;
  wire _0240_;
  wire _0241_;
  wire _0242_;
  wire _0243_;
  wire _0244_;
  wire _0245_;
  wire _0246_;
  wire _0247_;
  wire _0248_;
  wire _0249_;
  wire _0250_;
  wire _0251_;
  wire _0252_;
  wire _0253_;
  wire _0254_;
  wire _0255_;
  wire _0256_;
  wire _0257_;
  wire _0258_;
  wire _0259_;
  wire _0260_;
  wire _0261_;
  wire _0262_;
  wire _0263_;
  wire _0264_;
  wire _0265_;
  wire _0266_;
  wire _0267_;
  wire _0268_;
  wire _0269_;
  wire _0270_;
  wire _0271_;
  wire _0272_;
  wire _0273_;
  wire _0274_;
  wire _0275_;
  wire _0276_;
  wire _0277_;
  wire _0278_;
  wire _0279_;
  wire _0280_;
  wire _0281_;
  wire _0282_;
  wire _0283_;
  wire _0284_;
  wire _0285_;
  wire _0286_;
  wire _0287_;
  wire _0288_;
  wire _0289_;
  wire _0290_;
  wire _0291_;
  wire _0292_;
  wire _0293_;
  wire _0294_;
  wire _0295_;
  wire _0296_;
  wire _0297_;
  wire _0298_;
  wire _0299_;
  wire _0300_;
  wire _0301_;
  wire _0302_;
  wire _0303_;
  wire _0304_;
  wire _0305_;
  wire _0306_;
  wire _0307_;
  wire _0308_;
  wire _0309_;
  wire _0310_;
  wire _0311_;
  wire _0312_;
  wire _0313_;
  wire _0314_;
  wire _0315_;
  wire _0316_;
  wire _0317_;
  wire _0318_;
  wire _0319_;
  wire _0320_;
  wire _0321_;
  wire _0322_;
  wire _0323_;
  wire _0324_;
  wire _0325_;
  wire _0326_;
  wire _0327_;
  wire _0328_;
  wire _0329_;
  wire _0330_;
  wire _0331_;
  wire _0332_;
  wire _0333_;
  wire _0334_;
  wire _0335_;
  wire _0336_;
  wire _0337_;
  wire _0338_;
  wire _0339_;
  wire _0340_;
  wire _0341_;
  wire _0342_;
  wire _0343_;
  wire _0344_;
  wire _0345_;
  wire _0346_;
  wire _0347_;
  wire _0348_;
  wire _0349_;
  wire _0350_;
  wire _0351_;
  wire _0352_;
  wire _0353_;
  wire _0354_;
  wire _0355_;
  wire _0356_;
  wire _0357_;
  wire _0358_;
  wire _0359_;
  wire _0360_;
  wire _0361_;
  wire _0362_;
  wire _0363_;
  wire _0364_;
  wire _0365_;
  wire _0366_;
  wire _0367_;
  wire _0368_;
  wire _0369_;
  wire _0370_;
  wire _0371_;
  wire _0372_;
  wire _0373_;
  wire _0374_;
  wire _0375_;
  wire _0376_;
  wire _0377_;
  wire _0378_;
  wire _0379_;
  wire _0380_;
  wire _0381_;
  wire _0382_;
  wire _0383_;
  wire _0384_;
  wire _0385_;
  wire _0386_;
  wire _0387_;
  wire _0388_;
  wire _0389_;
  wire _0390_;
  wire _0391_;
  wire _0392_;
  wire _0393_;
  wire _0394_;
  wire _0395_;
  wire _0396_;
  wire _0397_;
  wire _0398_;
  wire _0399_;
  wire _0400_;
  wire _0401_;
  wire _0402_;
  wire _0403_;
  wire _0404_;
  wire _0405_;
  wire _0406_;
  wire _0407_;
  wire _0408_;
  wire _0409_;
  wire _0410_;
  wire _0411_;
  wire _0412_;
  wire _0413_;
  wire _0414_;
  wire _0415_;
  wire _0416_;
  wire _0417_;
  wire _0418_;
  wire _0419_;
  wire _0420_;
  wire _0421_;
  wire _0422_;
  wire _0423_;
  wire _0424_;
  wire _0425_;
  wire _0426_;
  wire _0427_;
  wire _0428_;
  wire _0429_;
  wire _0430_;
  wire _0431_;
  wire clk_scaled;
  wire \clk_scaler.counter[0] ;
  wire \clk_scaler.counter[10] ;
  wire \clk_scaler.counter[1] ;
  wire \clk_scaler.counter[2] ;
  wire \clk_scaler.counter[3] ;
  wire \clk_scaler.counter[4] ;
  wire \clk_scaler.counter[5] ;
  wire \clk_scaler.counter[6] ;
  wire \clk_scaler.counter[7] ;
  wire \clk_scaler.counter[8] ;
  wire \clk_scaler.counter[9] ;
  wire \signal_gen.enableA ;
  wire \signal_gen.enableN ;
  wire \signal_gen.enableVib ;
  wire \signal_gen.envA[0] ;
  wire \signal_gen.envA[1] ;
  wire \signal_gen.envA[2] ;
  wire \signal_gen.envA[3] ;
  wire \signal_gen.envA_gen.state[0] ;
  wire \signal_gen.envA_gen.state[1] ;
  wire \signal_gen.envA_gen.timer[0] ;
  wire \signal_gen.envA_gen.timer[1] ;
  wire \signal_gen.envA_gen.timer[2] ;
  wire \signal_gen.envA_gen.timer[3] ;
  wire \signal_gen.mix.a_val[0] ;
  wire \signal_gen.mix.a_val[1] ;
  wire \signal_gen.mix.a_val[2] ;
  wire \signal_gen.mix.a_val[3] ;
  wire \signal_gen.mix.a_val[4] ;
  wire \signal_gen.mix.mixout[2] ;
  wire \signal_gen.mix.mixout[3] ;
  wire \signal_gen.mix.mixout[4] ;
  wire \signal_gen.mix.mixout[5] ;
  wire \signal_gen.mix.mixout[6] ;
  wire \signal_gen.mix.mixout[7] ;
  wire \signal_gen.mix.multA[3] ;
  wire \signal_gen.mix.multA[4] ;
  wire \signal_gen.mix.multA[5] ;
  wire \signal_gen.mix.multA[6] ;
  wire \signal_gen.mix.multA[7] ;
  wire \signal_gen.mix.n_val[1] ;
  wire \signal_gen.mix.n_val[2] ;
  wire \signal_gen.mix.n_val[3] ;
  wire \signal_gen.mix.n_val[4] ;
  wire \signal_gen.mix.started ;
  wire \signal_gen.mix.sum[0] ;
  wire \signal_gen.mix.sum[1] ;
  wire \signal_gen.mix.sum[2] ;
  wire \signal_gen.mix.sum[3] ;
  wire \signal_gen.mix.sum[4] ;
  wire \signal_gen.mix.sum[5] ;
  wire \signal_gen.mix.waveA ;
  wire \signal_gen.n.feedback ;
  wire \signal_gen.n.noise_out ;
  wire \signal_gen.n.noise_reg[0] ;
  wire \signal_gen.n.noise_reg[10] ;
  wire \signal_gen.n.noise_reg[11] ;
  wire \signal_gen.n.noise_reg[12] ;
  wire \signal_gen.n.noise_reg[13] ;
  wire \signal_gen.n.noise_reg[1] ;
  wire \signal_gen.n.noise_reg[2] ;
  wire \signal_gen.n.noise_reg[3] ;
  wire \signal_gen.n.noise_reg[4] ;
  wire \signal_gen.n.noise_reg[5] ;
  wire \signal_gen.n.noise_reg[6] ;
  wire \signal_gen.n.noise_reg[7] ;
  wire \signal_gen.n.noise_reg[8] ;
  wire \signal_gen.n.noise_reg[9] ;
  wire \signal_gen.periodA[0] ;
  wire \signal_gen.periodA[1] ;
  wire \signal_gen.periodA[2] ;
  wire \signal_gen.periodA[3] ;
  wire \signal_gen.periodA[4] ;
  wire \signal_gen.pwm.clk_cnt[0] ;
  wire \signal_gen.pwm.clk_cnt[1] ;
  wire \signal_gen.pwm.clk_cnt[2] ;
  wire \signal_gen.pwm.clk_cnt[3] ;
  wire \signal_gen.pwm.clk_cnt[4] ;
  wire \signal_gen.pwm.clk_cnt[5] ;
  wire \signal_gen.pwm.clk_cnt[6] ;
  wire \signal_gen.pwm.clk_cnt[7] ;
  wire \signal_gen.pwm.pwm_o ;
  wire \signal_gen.tA.cnt[0] ;
  wire \signal_gen.tA.cnt[10] ;
  wire \signal_gen.tA.cnt[11] ;
  wire \signal_gen.tA.cnt[1] ;
  wire \signal_gen.tA.cnt[2] ;
  wire \signal_gen.tA.cnt[3] ;
  wire \signal_gen.tA.cnt[4] ;
  wire \signal_gen.tA.cnt[5] ;
  wire \signal_gen.tA.cnt[6] ;
  wire \signal_gen.tA.cnt[7] ;
  wire \signal_gen.tA.cnt[8] ;
  wire \signal_gen.tA.cnt[9] ;
  wire \signal_gen.vibA[0] ;
  wire \signal_gen.vibA[1] ;
  wire \signal_gen.vibA[2] ;
  wire \signal_gen.vibA[3] ;
  wire \signal_gen.vibA_gen.dir ;
  wire \signal_gen.vibA_gen.div[0] ;
  wire \signal_gen.vibA_gen.div[1] ;
  wire \signal_gen.vibA_gen.div[2] ;
  wire \signal_gen.vibA_gen.div[3] ;
  wire \signal_gen.vibA_gen.div[4] ;
  wire \signal_gen.vibA_gen.div[5] ;
  wire \signal_gen.vibA_gen.div[6] ;
  wire \signal_gen.vibA_gen.div[7] ;
  wire \signal_gen.vibA_gen.val[0] ;
  wire \signal_gen.vibA_gen.val[1] ;
  wire \signal_gen.vibA_gen.val[2] ;
  wire \signal_gen.vibA_gen.val[3] ;
  wire \signal_gen.vib_depth[0] ;
  wire \signal_gen.vib_depth[1] ;
  wire \signal_gen.vib_depth[2] ;
  wire \signal_gen.vib_depth[3] ;
  wire \signal_gen.volA[0] ;
  wire \signal_gen.volA[1] ;
  wire \signal_gen.volA[2] ;
  wire \signal_gen.volA[3] ;
  wire \signal_gen.volN[0] ;
  wire \signal_gen.volN[1] ;
  wire \signal_gen.volN[2] ;
  wire \signal_gen.volN[3] ;
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _0432_ (
    .I(\signal_gen.n.noise_reg[3] ),
    .ZN(_0122_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _0433_ (
    .I(\signal_gen.n.noise_reg[2] ),
    .ZN(_0123_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _0434_ (
    .I(\signal_gen.n.noise_reg[1] ),
    .ZN(_0124_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _0435_ (
    .I(\signal_gen.n.noise_reg[0] ),
    .ZN(_0125_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _0436_ (
    .I(\signal_gen.vibA_gen.val[3] ),
    .ZN(_0126_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _0437_ (
    .I(\signal_gen.vibA_gen.val[2] ),
    .ZN(_0127_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _0438_ (
    .I(\signal_gen.vibA_gen.val[1] ),
    .ZN(_0128_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _0439_ (
    .I(\signal_gen.vibA_gen.val[0] ),
    .ZN(_0129_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _0440_ (
    .I(\signal_gen.n.noise_reg[13] ),
    .ZN(_0130_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _0441_ (
    .I(\signal_gen.n.noise_reg[11] ),
    .ZN(_0131_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _0442_ (
    .I(\signal_gen.n.noise_reg[10] ),
    .ZN(_0132_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _0443_ (
    .I(\signal_gen.n.noise_reg[8] ),
    .ZN(_0133_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _0444_ (
    .I(\signal_gen.n.noise_reg[7] ),
    .ZN(_0134_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _0445_ (
    .I(\signal_gen.n.noise_reg[6] ),
    .ZN(_0135_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _0446_ (
    .I(\signal_gen.n.noise_reg[5] ),
    .ZN(_0136_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _0447_ (
    .I(\signal_gen.envA_gen.state[1] ),
    .ZN(_0137_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _0448_ (
    .I(\clk_scaler.counter[1] ),
    .ZN(_0138_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _0449_ (
    .I(\clk_scaler.counter[4] ),
    .ZN(_0139_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _0450_ (
    .I(rst_n),
    .ZN(_0140_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _0451_ (
    .I(\signal_gen.enableVib ),
    .ZN(_0141_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _0452_ (
    .I(ena),
    .ZN(_0142_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _0453_ (
    .I(uio_in[1]),
    .ZN(_0143_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _0454_ (
    .I(ui_in[0]),
    .ZN(_0144_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _0455_ (
    .I(\signal_gen.envA[1] ),
    .ZN(_0145_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _0456_ (
    .I(\signal_gen.envA[2] ),
    .ZN(_0146_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _0457_ (
    .I(\signal_gen.envA[3] ),
    .ZN(_0147_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _0458_ (
    .I(\signal_gen.pwm.clk_cnt[7] ),
    .ZN(_0148_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _0459_ (
    .I(\signal_gen.mix.mixout[6] ),
    .ZN(_0149_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _0460_ (
    .I(\signal_gen.mix.mixout[5] ),
    .ZN(_0150_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _0461_ (
    .I(\signal_gen.pwm.clk_cnt[4] ),
    .ZN(_0151_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _0462_ (
    .I(\signal_gen.pwm.clk_cnt[3] ),
    .ZN(_0152_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _0463_ (
    .I(\signal_gen.pwm.clk_cnt[2] ),
    .ZN(_0153_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _0464_ (
    .A1(\signal_gen.tA.cnt[0] ),
    .A2(\signal_gen.tA.cnt[1] ),
    .ZN(_0154_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or4_1 _0465_ (
    .A1(\signal_gen.tA.cnt[0] ),
    .A2(\signal_gen.tA.cnt[1] ),
    .A3(\signal_gen.tA.cnt[3] ),
    .A4(\signal_gen.tA.cnt[2] ),
    .Z(_0155_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or2_1 _0466_ (
    .A1(\signal_gen.tA.cnt[4] ),
    .A2(_0155_),
    .Z(_0156_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or3_1 _0467_ (
    .A1(\signal_gen.tA.cnt[5] ),
    .A2(\signal_gen.tA.cnt[6] ),
    .A3(_0156_),
    .Z(_0157_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or2_1 _0468_ (
    .A1(\signal_gen.tA.cnt[7] ),
    .A2(_0157_),
    .Z(_0158_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _0469_ (
    .A1(\signal_gen.tA.cnt[8] ),
    .A2(_0158_),
    .ZN(_0159_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or4_1 _0470_ (
    .A1(\signal_gen.tA.cnt[9] ),
    .A2(\signal_gen.tA.cnt[8] ),
    .A3(\signal_gen.tA.cnt[10] ),
    .A4(_0158_),
    .Z(_0160_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _0471_ (
    .A1(\signal_gen.tA.cnt[11] ),
    .A2(_0160_),
    .ZN(_0161_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _0472_ (
    .A1(\signal_gen.tA.cnt[11] ),
    .A2(_0160_),
    .B(\signal_gen.enableA ),
    .ZN(_0162_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _0473_ (
    .A1(\signal_gen.vibA[0] ),
    .A2(\signal_gen.periodA[0] ),
    .ZN(_0163_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or2_1 _0474_ (
    .A1(\signal_gen.vibA[0] ),
    .A2(\signal_gen.periodA[0] ),
    .Z(_0164_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _0475_ (
    .A1(_0162_),
    .A2(_0163_),
    .A3(_0164_),
    .ZN(_0165_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _0476_ (
    .A1(\signal_gen.tA.cnt[0] ),
    .A2(_0162_),
    .B(_0165_),
    .ZN(_0000_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _0477_ (
    .A1(\signal_gen.tA.cnt[0] ),
    .A2(\signal_gen.tA.cnt[1] ),
    .Z(_0166_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _0478_ (
    .A1(\signal_gen.vibA[1] ),
    .A2(\signal_gen.periodA[1] ),
    .ZN(_0167_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _0479_ (
    .A1(\signal_gen.vibA[1] ),
    .A2(\signal_gen.periodA[1] ),
    .ZN(_0168_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xnor3_1 _0480_ (
    .A1(\signal_gen.vibA[1] ),
    .A2(\signal_gen.periodA[1] ),
    .A3(_0163_),
    .ZN(_0169_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _0481_ (
    .A1(_0162_),
    .A2(_0169_),
    .ZN(_0170_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _0482_ (
    .A1(_0162_),
    .A2(_0166_),
    .B(_0170_),
    .ZN(_0003_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xnor2_1 _0483_ (
    .A1(\signal_gen.tA.cnt[2] ),
    .A2(_0154_),
    .ZN(_0171_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _0484_ (
    .A1(\signal_gen.vibA[2] ),
    .A2(\signal_gen.periodA[2] ),
    .Z(_0172_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _0485_ (
    .A1(\signal_gen.vibA[2] ),
    .A2(\signal_gen.periodA[2] ),
    .Z(_0173_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _0486_ (
    .A1(_0163_),
    .A2(_0168_),
    .B(_0167_),
    .ZN(_0174_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _0487_ (
    .A1(_0173_),
    .A2(_0174_),
    .Z(_0175_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _0488_ (
    .A1(_0162_),
    .A2(_0175_),
    .ZN(_0176_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _0489_ (
    .A1(_0162_),
    .A2(_0171_),
    .B(_0176_),
    .ZN(_0004_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _0490_ (
    .A1(\signal_gen.vibA[3] ),
    .A2(\signal_gen.periodA[3] ),
    .ZN(_0177_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _0491_ (
    .A1(\signal_gen.vibA[3] ),
    .A2(\signal_gen.periodA[3] ),
    .ZN(_0178_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _0492_ (
    .A1(_0173_),
    .A2(_0174_),
    .B(_0172_),
    .ZN(_0179_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor3_1 _0493_ (
    .A1(\signal_gen.vibA[3] ),
    .A2(\signal_gen.periodA[3] ),
    .A3(_0179_),
    .Z(_0180_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai31_1 _0494_ (
    .A1(\signal_gen.tA.cnt[0] ),
    .A2(\signal_gen.tA.cnt[1] ),
    .A3(\signal_gen.tA.cnt[2] ),
    .B(\signal_gen.tA.cnt[3] ),
    .ZN(_0181_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _0495_ (
    .A1(_0155_),
    .A2(_0181_),
    .ZN(_0182_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _0496_ (
    .A1(_0162_),
    .A2(_0182_),
    .ZN(_0183_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _0497_ (
    .A1(_0162_),
    .A2(_0180_),
    .B(_0183_),
    .ZN(_0005_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _0498_ (
    .A1(\signal_gen.tA.cnt[4] ),
    .A2(_0155_),
    .Z(_0184_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _0499_ (
    .A1(_0178_),
    .A2(_0179_),
    .B(_0177_),
    .ZN(_0185_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _0500_ (
    .A1(\signal_gen.periodA[4] ),
    .A2(_0185_),
    .Z(_0186_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _0501_ (
    .A1(_0162_),
    .A2(_0186_),
    .ZN(_0187_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _0502_ (
    .A1(_0162_),
    .A2(_0184_),
    .B(_0187_),
    .ZN(_0006_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _0503_ (
    .A1(\signal_gen.tA.cnt[5] ),
    .A2(_0156_),
    .Z(_0188_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _0504_ (
    .A1(\signal_gen.periodA[4] ),
    .A2(_0162_),
    .A3(_0185_),
    .ZN(_0189_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _0505_ (
    .A1(_0162_),
    .A2(_0188_),
    .B(_0189_),
    .ZN(_0007_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _0506_ (
    .A1(\signal_gen.tA.cnt[5] ),
    .A2(_0156_),
    .B(\signal_gen.tA.cnt[6] ),
    .ZN(_0190_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _0507_ (
    .A1(\signal_gen.enableA ),
    .A2(_0157_),
    .A3(_0190_),
    .ZN(_0008_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _0508_ (
    .A1(\signal_gen.tA.cnt[7] ),
    .A2(_0157_),
    .ZN(_0191_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _0509_ (
    .A1(\signal_gen.enableA ),
    .A2(_0158_),
    .A3(_0191_),
    .ZN(_0009_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _0510_ (
    .A1(\signal_gen.tA.cnt[8] ),
    .A2(_0158_),
    .Z(_0192_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _0511_ (
    .A1(_0162_),
    .A2(_0192_),
    .ZN(_0010_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xnor2_1 _0512_ (
    .A1(\signal_gen.tA.cnt[9] ),
    .A2(_0159_),
    .ZN(_0193_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _0513_ (
    .A1(_0162_),
    .A2(_0193_),
    .ZN(_0011_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai31_1 _0514_ (
    .A1(\signal_gen.tA.cnt[9] ),
    .A2(\signal_gen.tA.cnt[8] ),
    .A3(_0158_),
    .B(\signal_gen.tA.cnt[10] ),
    .ZN(_0194_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _0515_ (
    .A1(_0160_),
    .A2(_0194_),
    .B(_0162_),
    .ZN(_0001_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and3_1 _0516_ (
    .A1(\signal_gen.enableA ),
    .A2(\signal_gen.tA.cnt[11] ),
    .A3(_0160_),
    .Z(_0002_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _0517_ (
    .A1(\signal_gen.enableN ),
    .A2(\signal_gen.n.noise_reg[4] ),
    .B(rst_n),
    .ZN(_0195_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _0518_ (
    .A1(_0122_),
    .A2(\signal_gen.enableN ),
    .B(_0195_),
    .ZN(_0012_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _0519_ (
    .A1(\signal_gen.enableN ),
    .A2(\signal_gen.n.noise_reg[4] ),
    .ZN(_0196_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai211_1 _0520_ (
    .A1(\signal_gen.enableN ),
    .A2(_0136_),
    .B(rst_n),
    .C(_0196_),
    .ZN(_0013_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _0521_ (
    .A1(\signal_gen.enableN ),
    .A2(\signal_gen.n.noise_reg[5] ),
    .ZN(_0197_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai211_1 _0522_ (
    .A1(\signal_gen.enableN ),
    .A2(_0135_),
    .B(rst_n),
    .C(_0197_),
    .ZN(_0014_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _0523_ (
    .A1(\signal_gen.enableN ),
    .A2(\signal_gen.n.noise_reg[6] ),
    .ZN(_0198_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai211_1 _0524_ (
    .A1(\signal_gen.enableN ),
    .A2(_0134_),
    .B(rst_n),
    .C(_0198_),
    .ZN(_0015_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _0525_ (
    .A1(\signal_gen.enableN ),
    .A2(\signal_gen.n.noise_reg[8] ),
    .B(rst_n),
    .ZN(_0199_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _0526_ (
    .A1(\signal_gen.enableN ),
    .A2(_0134_),
    .B(_0199_),
    .ZN(_0016_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _0527_ (
    .A1(\signal_gen.enableN ),
    .A2(\signal_gen.n.noise_reg[9] ),
    .B(rst_n),
    .ZN(_0200_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _0528_ (
    .A1(\signal_gen.enableN ),
    .A2(_0133_),
    .B(_0200_),
    .ZN(_0017_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _0529_ (
    .A1(\signal_gen.enableN ),
    .A2(\signal_gen.n.noise_reg[9] ),
    .ZN(_0201_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai211_1 _0530_ (
    .A1(\signal_gen.enableN ),
    .A2(_0132_),
    .B(rst_n),
    .C(_0201_),
    .ZN(_0018_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _0531_ (
    .A1(\signal_gen.enableN ),
    .A2(\signal_gen.n.noise_reg[10] ),
    .ZN(_0202_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai211_1 _0532_ (
    .A1(\signal_gen.enableN ),
    .A2(_0131_),
    .B(rst_n),
    .C(_0202_),
    .ZN(_0019_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _0533_ (
    .A1(\signal_gen.enableN ),
    .A2(\signal_gen.n.noise_reg[12] ),
    .B(rst_n),
    .ZN(_0203_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _0534_ (
    .A1(\signal_gen.enableN ),
    .A2(_0131_),
    .B(_0203_),
    .ZN(_0020_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _0535_ (
    .A1(\signal_gen.enableN ),
    .A2(\signal_gen.n.noise_reg[12] ),
    .ZN(_0204_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai211_1 _0536_ (
    .A1(\signal_gen.enableN ),
    .A2(_0130_),
    .B(rst_n),
    .C(_0204_),
    .ZN(_0021_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _0537_ (
    .A1(uio_in[0]),
    .A2(_0143_),
    .ZN(_0205_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _0538_ (
    .A1(uio_in[2]),
    .A2(ui_in[0]),
    .A3(_0205_),
    .ZN(_0206_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _0539_ (
    .I0(ui_in[4]),
    .I1(\signal_gen.vib_depth[0] ),
    .S(_0206_),
    .Z(_0022_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _0540_ (
    .I0(ui_in[5]),
    .I1(\signal_gen.vib_depth[1] ),
    .S(_0206_),
    .Z(_0023_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _0541_ (
    .I0(ui_in[6]),
    .I1(\signal_gen.vib_depth[2] ),
    .S(_0206_),
    .Z(_0024_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _0542_ (
    .I0(ui_in[7]),
    .I1(\signal_gen.vib_depth[3] ),
    .S(_0206_),
    .Z(_0025_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _0543_ (
    .A1(\signal_gen.mix.started ),
    .A2(_0140_),
    .ZN(_0207_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _0544_ (
    .A1(\signal_gen.mix.started ),
    .A2(rst_n),
    .Z(_0208_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _0545_ (
    .A1(\signal_gen.mix.started ),
    .A2(rst_n),
    .ZN(_0209_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _0546_ (
    .A1(\signal_gen.enableN ),
    .A2(rst_n),
    .ZN(_0210_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and3_1 _0547_ (
    .A1(\signal_gen.enableN ),
    .A2(\signal_gen.n.noise_out ),
    .A3(_0208_),
    .Z(_0211_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _0548_ (
    .A1(\signal_gen.mix.n_val[1] ),
    .A2(_0207_),
    .B1(_0211_),
    .B2(\signal_gen.volN[0] ),
    .ZN(_0212_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _0549_ (
    .I(_0212_),
    .ZN(_0026_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _0550_ (
    .A1(\signal_gen.mix.n_val[2] ),
    .A2(_0207_),
    .B1(_0211_),
    .B2(\signal_gen.volN[1] ),
    .ZN(_0213_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _0551_ (
    .I(_0213_),
    .ZN(_0027_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _0552_ (
    .A1(\signal_gen.mix.n_val[3] ),
    .A2(_0207_),
    .B1(_0211_),
    .B2(\signal_gen.volN[2] ),
    .ZN(_0214_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _0553_ (
    .I(_0214_),
    .ZN(_0028_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _0554_ (
    .A1(\signal_gen.mix.n_val[4] ),
    .A2(_0207_),
    .B1(_0211_),
    .B2(\signal_gen.volN[3] ),
    .ZN(_0215_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _0555_ (
    .I(_0215_),
    .ZN(_0029_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _0556_ (
    .A1(\signal_gen.pwm.clk_cnt[0] ),
    .A2(_0140_),
    .ZN(_0030_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _0557_ (
    .A1(\signal_gen.pwm.clk_cnt[0] ),
    .A2(\signal_gen.pwm.clk_cnt[1] ),
    .B(rst_n),
    .ZN(_0216_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _0558_ (
    .A1(\signal_gen.pwm.clk_cnt[0] ),
    .A2(\signal_gen.pwm.clk_cnt[1] ),
    .B(_0216_),
    .ZN(_0031_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _0559_ (
    .A1(\signal_gen.pwm.clk_cnt[0] ),
    .A2(\signal_gen.pwm.clk_cnt[1] ),
    .B(\signal_gen.pwm.clk_cnt[2] ),
    .ZN(_0217_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and3_1 _0560_ (
    .A1(\signal_gen.pwm.clk_cnt[0] ),
    .A2(\signal_gen.pwm.clk_cnt[2] ),
    .A3(\signal_gen.pwm.clk_cnt[1] ),
    .Z(_0218_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _0561_ (
    .A1(_0140_),
    .A2(_0217_),
    .A3(_0218_),
    .ZN(_0032_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _0562_ (
    .A1(\signal_gen.pwm.clk_cnt[3] ),
    .A2(_0218_),
    .Z(_0219_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _0563_ (
    .A1(\signal_gen.pwm.clk_cnt[3] ),
    .A2(_0218_),
    .B(rst_n),
    .ZN(_0220_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _0564_ (
    .A1(_0219_),
    .A2(_0220_),
    .ZN(_0033_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _0565_ (
    .A1(\signal_gen.pwm.clk_cnt[4] ),
    .A2(_0219_),
    .Z(_0221_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _0566_ (
    .A1(\signal_gen.pwm.clk_cnt[4] ),
    .A2(_0219_),
    .B(rst_n),
    .ZN(_0222_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _0567_ (
    .A1(_0221_),
    .A2(_0222_),
    .ZN(_0034_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _0568_ (
    .A1(\signal_gen.pwm.clk_cnt[5] ),
    .A2(_0221_),
    .Z(_0223_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _0569_ (
    .A1(\signal_gen.pwm.clk_cnt[5] ),
    .A2(_0221_),
    .B(rst_n),
    .ZN(_0224_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _0570_ (
    .A1(_0223_),
    .A2(_0224_),
    .ZN(_0035_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _0571_ (
    .A1(\signal_gen.pwm.clk_cnt[6] ),
    .A2(_0223_),
    .ZN(_0225_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _0572_ (
    .A1(\signal_gen.pwm.clk_cnt[6] ),
    .A2(_0223_),
    .B(rst_n),
    .ZN(_0226_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _0573_ (
    .A1(\signal_gen.pwm.clk_cnt[6] ),
    .A2(_0223_),
    .B(_0226_),
    .ZN(_0036_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _0574_ (
    .A1(\signal_gen.pwm.clk_cnt[7] ),
    .A2(_0225_),
    .Z(_0227_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _0575_ (
    .A1(_0140_),
    .A2(_0227_),
    .ZN(_0037_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _0576_ (
    .A1(\signal_gen.vibA_gen.div[4] ),
    .A2(\signal_gen.vibA_gen.div[5] ),
    .ZN(_0228_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor4_1 _0577_ (
    .A1(\signal_gen.vibA_gen.div[2] ),
    .A2(\signal_gen.vibA_gen.div[7] ),
    .A3(\signal_gen.vibA_gen.div[6] ),
    .A4(_0228_),
    .ZN(_0229_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _0578_ (
    .A1(\signal_gen.vibA_gen.div[0] ),
    .A2(\signal_gen.vibA_gen.div[3] ),
    .ZN(_0230_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and3_1 _0579_ (
    .A1(\signal_gen.vibA_gen.div[1] ),
    .A2(_0229_),
    .A3(_0230_),
    .Z(_0231_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _0580_ (
    .I(_0231_),
    .ZN(_0232_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _0581_ (
    .A1(\signal_gen.vibA[0] ),
    .A2(_0231_),
    .B(\signal_gen.enableVib ),
    .ZN(_0233_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _0582_ (
    .A1(_0129_),
    .A2(_0231_),
    .B(_0233_),
    .ZN(_0038_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _0583_ (
    .A1(\signal_gen.vibA[1] ),
    .A2(_0231_),
    .B(\signal_gen.enableVib ),
    .ZN(_0234_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _0584_ (
    .A1(_0128_),
    .A2(_0231_),
    .B(_0234_),
    .ZN(_0039_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _0585_ (
    .A1(\signal_gen.vibA[2] ),
    .A2(_0231_),
    .B(\signal_gen.enableVib ),
    .ZN(_0235_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _0586_ (
    .A1(_0127_),
    .A2(_0231_),
    .B(_0235_),
    .ZN(_0040_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _0587_ (
    .A1(\signal_gen.vibA[3] ),
    .A2(_0231_),
    .B(\signal_gen.enableVib ),
    .ZN(_0236_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _0588_ (
    .A1(_0126_),
    .A2(_0231_),
    .B(_0236_),
    .ZN(_0041_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _0589_ (
    .A1(\signal_gen.mix.waveA ),
    .A2(_0161_),
    .Z(_0237_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _0590_ (
    .A1(\signal_gen.enableA ),
    .A2(_0237_),
    .Z(_0042_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor4_1 _0591_ (
    .A1(\signal_gen.vibA_gen.val[3] ),
    .A2(\signal_gen.vibA_gen.val[2] ),
    .A3(\signal_gen.vibA_gen.val[1] ),
    .A4(\signal_gen.vibA_gen.val[0] ),
    .ZN(_0238_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _0592_ (
    .A1(_0231_),
    .A2(_0238_),
    .ZN(_0239_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai211_1 _0593_ (
    .A1(_0128_),
    .A2(\signal_gen.vib_depth[1] ),
    .B(\signal_gen.vib_depth[0] ),
    .C(_0129_),
    .ZN(_0240_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _0594_ (
    .A1(_0127_),
    .A2(\signal_gen.vib_depth[2] ),
    .B1(\signal_gen.vib_depth[1] ),
    .B2(_0128_),
    .ZN(_0241_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai22_1 _0595_ (
    .A1(_0126_),
    .A2(\signal_gen.vib_depth[3] ),
    .B1(\signal_gen.vib_depth[2] ),
    .B2(_0127_),
    .ZN(_0242_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _0596_ (
    .A1(_0240_),
    .A2(_0241_),
    .B(_0242_),
    .ZN(_0243_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi211_1 _0597_ (
    .A1(_0126_),
    .A2(\signal_gen.vib_depth[3] ),
    .B(_0243_),
    .C(\signal_gen.vibA_gen.dir ),
    .ZN(_0244_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _0598_ (
    .A1(\signal_gen.vibA_gen.dir ),
    .A2(_0239_),
    .B1(_0244_),
    .B2(_0231_),
    .ZN(_0245_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _0599_ (
    .A1(_0141_),
    .A2(_0245_),
    .ZN(_0043_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi211_1 _0600_ (
    .A1(\signal_gen.vibA_gen.dir ),
    .A2(_0238_),
    .B(_0244_),
    .C(_0232_),
    .ZN(_0246_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _0601_ (
    .A1(\signal_gen.vibA_gen.val[0] ),
    .A2(_0246_),
    .B(\signal_gen.enableVib ),
    .ZN(_0247_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _0602_ (
    .A1(\signal_gen.vibA_gen.val[0] ),
    .A2(_0246_),
    .B(_0247_),
    .ZN(_0044_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _0603_ (
    .A1(\signal_gen.vibA_gen.val[1] ),
    .A2(\signal_gen.vibA_gen.dir ),
    .Z(_0248_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _0604_ (
    .A1(\signal_gen.vibA_gen.val[1] ),
    .A2(\signal_gen.vibA_gen.dir ),
    .Z(_0249_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _0605_ (
    .A1(_0129_),
    .A2(_0249_),
    .Z(_0250_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _0606_ (
    .A1(\signal_gen.vibA_gen.val[1] ),
    .A2(_0246_),
    .B(\signal_gen.enableVib ),
    .ZN(_0251_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _0607_ (
    .A1(_0246_),
    .A2(_0250_),
    .B(_0251_),
    .ZN(_0045_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _0608_ (
    .A1(\signal_gen.vibA_gen.val[2] ),
    .A2(\signal_gen.vibA_gen.dir ),
    .ZN(_0252_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _0609_ (
    .A1(\signal_gen.vibA_gen.val[2] ),
    .A2(\signal_gen.vibA_gen.dir ),
    .ZN(_0253_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _0610_ (
    .A1(\signal_gen.vibA_gen.val[0] ),
    .A2(_0249_),
    .B(_0248_),
    .ZN(_0254_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor3_1 _0611_ (
    .A1(\signal_gen.vibA_gen.val[2] ),
    .A2(\signal_gen.vibA_gen.dir ),
    .A3(_0254_),
    .Z(_0255_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _0612_ (
    .A1(\signal_gen.vibA_gen.val[2] ),
    .A2(_0246_),
    .B(\signal_gen.enableVib ),
    .ZN(_0256_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _0613_ (
    .A1(_0246_),
    .A2(_0255_),
    .B(_0256_),
    .ZN(_0046_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _0614_ (
    .A1(_0252_),
    .A2(_0254_),
    .B(_0253_),
    .ZN(_0257_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor3_1 _0615_ (
    .A1(_0126_),
    .A2(\signal_gen.vibA_gen.dir ),
    .A3(_0257_),
    .Z(_0258_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _0616_ (
    .A1(\signal_gen.vibA_gen.val[3] ),
    .A2(_0246_),
    .B(\signal_gen.enableVib ),
    .ZN(_0259_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _0617_ (
    .A1(_0246_),
    .A2(_0258_),
    .B(_0259_),
    .ZN(_0047_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _0618_ (
    .A1(ui_in[3]),
    .A2(_0206_),
    .ZN(_0260_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _0619_ (
    .A1(_0141_),
    .A2(_0206_),
    .B(_0260_),
    .ZN(_0048_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and4_1 _0620_ (
    .A1(uio_in[0]),
    .A2(_0143_),
    .A3(uio_in[2]),
    .A4(ui_in[0]),
    .Z(_0261_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _0621_ (
    .I0(\signal_gen.enableN ),
    .I1(ui_in[3]),
    .S(_0261_),
    .Z(_0049_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _0622_ (
    .I0(\signal_gen.enableA ),
    .I1(ui_in[5]),
    .S(_0261_),
    .Z(_0050_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _0623_ (
    .A1(uio_in[0]),
    .A2(uio_in[1]),
    .ZN(_0262_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _0624_ (
    .A1(uio_in[2]),
    .A2(ui_in[0]),
    .A3(_0262_),
    .ZN(_0263_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _0625_ (
    .I0(ui_in[3]),
    .I1(\signal_gen.volN[0] ),
    .S(_0263_),
    .Z(_0051_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _0626_ (
    .I0(ui_in[4]),
    .I1(\signal_gen.volN[1] ),
    .S(_0263_),
    .Z(_0052_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _0627_ (
    .I0(ui_in[5]),
    .I1(\signal_gen.volN[2] ),
    .S(_0263_),
    .Z(_0053_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _0628_ (
    .I0(ui_in[6]),
    .I1(\signal_gen.volN[3] ),
    .S(_0263_),
    .Z(_0054_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _0629_ (
    .A1(uio_in[2]),
    .A2(_0144_),
    .ZN(_0264_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _0630_ (
    .A1(_0205_),
    .A2(_0264_),
    .ZN(_0265_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _0631_ (
    .I0(ui_in[3]),
    .I1(\signal_gen.volA[0] ),
    .S(_0265_),
    .Z(_0055_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _0632_ (
    .I0(ui_in[4]),
    .I1(\signal_gen.volA[1] ),
    .S(_0265_),
    .Z(_0056_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _0633_ (
    .I0(ui_in[5]),
    .I1(\signal_gen.volA[2] ),
    .S(_0265_),
    .Z(_0057_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _0634_ (
    .I0(ui_in[6]),
    .I1(\signal_gen.volA[3] ),
    .S(_0265_),
    .Z(_0058_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _0635_ (
    .A1(_0262_),
    .A2(_0264_),
    .ZN(_0266_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _0636_ (
    .I0(ui_in[3]),
    .I1(\signal_gen.periodA[0] ),
    .S(_0266_),
    .Z(_0059_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _0637_ (
    .I0(ui_in[4]),
    .I1(\signal_gen.periodA[1] ),
    .S(_0266_),
    .Z(_0060_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _0638_ (
    .I0(ui_in[5]),
    .I1(\signal_gen.periodA[2] ),
    .S(_0266_),
    .Z(_0061_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _0639_ (
    .I0(ui_in[6]),
    .I1(\signal_gen.periodA[3] ),
    .S(_0266_),
    .Z(_0062_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _0640_ (
    .I0(ui_in[7]),
    .I1(\signal_gen.periodA[4] ),
    .S(_0266_),
    .Z(_0063_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _0641_ (
    .A1(\signal_gen.envA_gen.state[1] ),
    .A2(\signal_gen.envA_gen.state[0] ),
    .ZN(_0267_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or2_1 _0642_ (
    .A1(\signal_gen.envA_gen.timer[0] ),
    .A2(_0267_),
    .Z(_0268_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi211_1 _0643_ (
    .A1(\signal_gen.envA_gen.timer[1] ),
    .A2(_0268_),
    .B(\signal_gen.envA_gen.timer[2] ),
    .C(\signal_gen.envA_gen.timer[3] ),
    .ZN(_0269_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand4_1 _0644_ (
    .A1(\signal_gen.envA_gen.state[0] ),
    .A2(\signal_gen.envA[1] ),
    .A3(\signal_gen.envA[2] ),
    .A4(\signal_gen.envA[3] ),
    .ZN(_0270_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _0645_ (
    .A1(\signal_gen.envA_gen.state[1] ),
    .A2(_0270_),
    .ZN(_0271_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _0646_ (
    .A1(\signal_gen.envA[0] ),
    .A2(\signal_gen.envA[1] ),
    .A3(\signal_gen.envA[2] ),
    .ZN(_0272_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _0647_ (
    .A1(\signal_gen.envA[3] ),
    .A2(_0267_),
    .ZN(_0273_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _0648_ (
    .A1(\signal_gen.envA[0] ),
    .A2(_0271_),
    .B1(_0272_),
    .B2(_0273_),
    .ZN(_0274_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _0649_ (
    .A1(\signal_gen.envA_gen.state[0] ),
    .A2(_0269_),
    .B(_0274_),
    .ZN(_0275_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _0650_ (
    .A1(\signal_gen.envA_gen.state[1] ),
    .A2(_0275_),
    .Z(_0064_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _0651_ (
    .A1(_0137_),
    .A2(\signal_gen.envA_gen.state[0] ),
    .ZN(_0276_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _0652_ (
    .A1(\signal_gen.envA_gen.state[1] ),
    .A2(\signal_gen.envA_gen.state[0] ),
    .ZN(_0277_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or2_1 _0653_ (
    .A1(\signal_gen.envA_gen.state[1] ),
    .A2(\signal_gen.envA_gen.state[0] ),
    .Z(_0278_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _0654_ (
    .A1(\signal_gen.enableA ),
    .A2(_0278_),
    .ZN(_0279_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi211_1 _0655_ (
    .A1(\signal_gen.enableA ),
    .A2(_0276_),
    .B(_0279_),
    .C(_0275_),
    .ZN(_0065_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _0656_ (
    .A1(\clk_scaler.counter[1] ),
    .A2(\clk_scaler.counter[3] ),
    .A3(\clk_scaler.counter[2] ),
    .ZN(_0280_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _0657_ (
    .A1(\clk_scaler.counter[5] ),
    .A2(\clk_scaler.counter[4] ),
    .ZN(_0281_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _0658_ (
    .A1(\clk_scaler.counter[7] ),
    .A2(\clk_scaler.counter[6] ),
    .ZN(_0282_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _0659_ (
    .A1(\clk_scaler.counter[8] ),
    .A2(\clk_scaler.counter[9] ),
    .A3(\clk_scaler.counter[10] ),
    .ZN(_0283_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai211_1 _0660_ (
    .A1(_0280_),
    .A2(_0281_),
    .B(_0282_),
    .C(_0283_),
    .ZN(_0284_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _0661_ (
    .A1(_0140_),
    .A2(_0284_),
    .ZN(_0285_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _0662_ (
    .A1(ena),
    .A2(_0285_),
    .ZN(_0286_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _0663_ (
    .A1(\clk_scaler.counter[0] ),
    .A2(_0142_),
    .ZN(_0287_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _0664_ (
    .A1(\clk_scaler.counter[0] ),
    .A2(_0286_),
    .B(_0287_),
    .ZN(_0066_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _0665_ (
    .A1(\clk_scaler.counter[0] ),
    .A2(\clk_scaler.counter[1] ),
    .ZN(_0288_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _0666_ (
    .A1(\clk_scaler.counter[0] ),
    .A2(\clk_scaler.counter[1] ),
    .Z(_0289_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai32_1 _0667_ (
    .A1(_0286_),
    .A2(_0288_),
    .A3(_0289_),
    .B1(ena),
    .B2(_0138_),
    .ZN(_0067_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _0668_ (
    .A1(\clk_scaler.counter[2] ),
    .A2(_0289_),
    .Z(_0290_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _0669_ (
    .A1(\clk_scaler.counter[2] ),
    .A2(_0289_),
    .ZN(_0291_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _0670_ (
    .A1(_0285_),
    .A2(_0291_),
    .ZN(_0292_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _0671_ (
    .A1(ena),
    .A2(_0292_),
    .ZN(_0293_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _0672_ (
    .A1(ena),
    .A2(_0289_),
    .B(\clk_scaler.counter[2] ),
    .ZN(_0294_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _0673_ (
    .A1(ena),
    .A2(_0292_),
    .B(_0294_),
    .ZN(_0068_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _0674_ (
    .A1(\clk_scaler.counter[3] ),
    .A2(_0293_),
    .ZN(_0295_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai31_1 _0675_ (
    .A1(\clk_scaler.counter[3] ),
    .A2(_0286_),
    .A3(_0291_),
    .B(_0295_),
    .ZN(_0069_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _0676_ (
    .A1(\clk_scaler.counter[3] ),
    .A2(\clk_scaler.counter[4] ),
    .A3(_0290_),
    .ZN(_0296_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _0677_ (
    .A1(_0285_),
    .A2(_0296_),
    .ZN(_0297_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _0678_ (
    .A1(ena),
    .A2(_0297_),
    .ZN(_0298_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _0679_ (
    .A1(\clk_scaler.counter[3] ),
    .A2(ena),
    .A3(_0290_),
    .ZN(_0299_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _0680_ (
    .A1(ena),
    .A2(_0297_),
    .B1(_0299_),
    .B2(_0139_),
    .ZN(_0070_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _0681_ (
    .A1(\clk_scaler.counter[5] ),
    .A2(_0298_),
    .ZN(_0300_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _0682_ (
    .A1(_0286_),
    .A2(_0296_),
    .B(_0300_),
    .ZN(_0071_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _0683_ (
    .A1(\clk_scaler.counter[6] ),
    .A2(_0142_),
    .Z(_0072_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _0684_ (
    .A1(\clk_scaler.counter[7] ),
    .A2(_0142_),
    .Z(_0073_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _0685_ (
    .A1(\clk_scaler.counter[8] ),
    .A2(_0142_),
    .Z(_0074_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _0686_ (
    .A1(\clk_scaler.counter[9] ),
    .A2(_0142_),
    .Z(_0075_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _0687_ (
    .A1(\clk_scaler.counter[10] ),
    .A2(_0142_),
    .Z(_0076_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai211_1 _0688_ (
    .A1(clk_scaled),
    .A2(_0284_),
    .B(ena),
    .C(rst_n),
    .ZN(_0301_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _0689_ (
    .A1(clk_scaled),
    .A2(_0284_),
    .B(_0301_),
    .ZN(_0077_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai31_1 _0690_ (
    .A1(\signal_gen.envA_gen.timer[1] ),
    .A2(\signal_gen.envA_gen.timer[3] ),
    .A3(\signal_gen.envA_gen.timer[2] ),
    .B(\signal_gen.envA[3] ),
    .ZN(_0302_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _0691_ (
    .A1(_0272_),
    .A2(_0302_),
    .B(_0276_),
    .ZN(_0303_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _0692_ (
    .A1(_0274_),
    .A2(_0303_),
    .ZN(_0304_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _0693_ (
    .A1(\signal_gen.envA_gen.state[0] ),
    .A2(_0269_),
    .B(_0304_),
    .ZN(_0305_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _0694_ (
    .A1(_0278_),
    .A2(_0305_),
    .ZN(_0306_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _0695_ (
    .A1(_0278_),
    .A2(_0305_),
    .B(\signal_gen.envA[0] ),
    .ZN(_0307_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _0696_ (
    .A1(\signal_gen.envA[0] ),
    .A2(_0305_),
    .B(_0307_),
    .ZN(_0078_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _0697_ (
    .A1(\signal_gen.envA_gen.state[1] ),
    .A2(\signal_gen.envA[1] ),
    .Z(_0308_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _0698_ (
    .A1(\signal_gen.envA[0] ),
    .A2(_0308_),
    .Z(_0309_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _0699_ (
    .A1(\signal_gen.envA[0] ),
    .A2(_0308_),
    .ZN(_0310_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai32_1 _0700_ (
    .A1(_0306_),
    .A2(_0309_),
    .A3(_0310_),
    .B1(_0305_),
    .B2(_0145_),
    .ZN(_0079_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _0701_ (
    .A1(\signal_gen.envA_gen.state[1] ),
    .A2(\signal_gen.envA[2] ),
    .ZN(_0311_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _0702_ (
    .A1(\signal_gen.envA_gen.state[1] ),
    .A2(\signal_gen.envA[2] ),
    .ZN(_0312_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _0703_ (
    .A1(\signal_gen.envA_gen.state[1] ),
    .A2(\signal_gen.envA[1] ),
    .B(_0309_),
    .ZN(_0313_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor3_1 _0704_ (
    .A1(\signal_gen.envA_gen.state[1] ),
    .A2(\signal_gen.envA[2] ),
    .A3(_0313_),
    .Z(_0314_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai22_1 _0705_ (
    .A1(_0146_),
    .A2(_0305_),
    .B1(_0306_),
    .B2(_0314_),
    .ZN(_0080_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _0706_ (
    .A1(_0312_),
    .A2(_0313_),
    .B(_0311_),
    .ZN(_0315_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor3_1 _0707_ (
    .A1(\signal_gen.envA_gen.state[1] ),
    .A2(_0147_),
    .A3(_0315_),
    .Z(_0316_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai22_1 _0708_ (
    .A1(_0147_),
    .A2(_0305_),
    .B1(_0306_),
    .B2(_0316_),
    .ZN(_0081_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _0709_ (
    .A1(\signal_gen.mix.sum[0] ),
    .A2(_0208_),
    .Z(_0082_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _0710_ (
    .A1(\signal_gen.mix.sum[1] ),
    .A2(_0208_),
    .Z(_0083_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _0711_ (
    .A1(\signal_gen.mix.sum[2] ),
    .A2(_0208_),
    .Z(_0084_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _0712_ (
    .A1(\signal_gen.mix.sum[3] ),
    .A2(_0208_),
    .Z(_0085_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _0713_ (
    .A1(\signal_gen.mix.sum[4] ),
    .A2(_0208_),
    .Z(_0086_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _0714_ (
    .A1(\signal_gen.mix.sum[5] ),
    .A2(_0208_),
    .Z(_0087_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _0715_ (
    .A1(\signal_gen.enableVib ),
    .A2(_0232_),
    .ZN(_0317_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _0716_ (
    .A1(\signal_gen.vibA_gen.div[0] ),
    .A2(_0317_),
    .ZN(_0088_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xnor2_1 _0717_ (
    .A1(\signal_gen.vibA_gen.div[0] ),
    .A2(\signal_gen.vibA_gen.div[1] ),
    .ZN(_0318_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _0718_ (
    .A1(_0317_),
    .A2(_0318_),
    .ZN(_0089_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and3_1 _0719_ (
    .A1(\signal_gen.vibA_gen.div[0] ),
    .A2(\signal_gen.vibA_gen.div[1] ),
    .A3(\signal_gen.vibA_gen.div[2] ),
    .Z(_0319_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _0720_ (
    .A1(\signal_gen.vibA_gen.div[0] ),
    .A2(\signal_gen.vibA_gen.div[1] ),
    .B(\signal_gen.vibA_gen.div[2] ),
    .ZN(_0320_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _0721_ (
    .A1(_0317_),
    .A2(_0319_),
    .A3(_0320_),
    .ZN(_0090_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _0722_ (
    .A1(\signal_gen.vibA_gen.div[3] ),
    .A2(_0319_),
    .Z(_0321_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _0723_ (
    .A1(\signal_gen.vibA_gen.div[3] ),
    .A2(_0319_),
    .ZN(_0322_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _0724_ (
    .A1(_0317_),
    .A2(_0321_),
    .A3(_0322_),
    .ZN(_0091_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _0725_ (
    .A1(\signal_gen.vibA_gen.div[4] ),
    .A2(_0321_),
    .Z(_0323_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _0726_ (
    .A1(\signal_gen.vibA_gen.div[4] ),
    .A2(_0321_),
    .ZN(_0324_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _0727_ (
    .A1(_0317_),
    .A2(_0323_),
    .A3(_0324_),
    .ZN(_0092_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _0728_ (
    .A1(\signal_gen.vibA_gen.div[5] ),
    .A2(_0323_),
    .ZN(_0325_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _0729_ (
    .A1(\signal_gen.vibA_gen.div[5] ),
    .A2(_0323_),
    .Z(_0326_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _0730_ (
    .A1(_0317_),
    .A2(_0325_),
    .A3(_0326_),
    .ZN(_0093_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _0731_ (
    .A1(\signal_gen.vibA_gen.div[6] ),
    .A2(_0326_),
    .ZN(_0327_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xnor2_1 _0732_ (
    .A1(\signal_gen.vibA_gen.div[6] ),
    .A2(_0326_),
    .ZN(_0328_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _0733_ (
    .A1(_0317_),
    .A2(_0328_),
    .ZN(_0094_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _0734_ (
    .A1(\signal_gen.vibA_gen.div[7] ),
    .A2(_0327_),
    .Z(_0329_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _0735_ (
    .A1(_0317_),
    .A2(_0329_),
    .ZN(_0095_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _0736_ (
    .A1(\signal_gen.n.noise_reg[13] ),
    .A2(\signal_gen.n.noise_reg[4] ),
    .Z(_0330_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _0737_ (
    .A1(\signal_gen.n.feedback ),
    .A2(_0210_),
    .ZN(_0331_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _0738_ (
    .A1(_0210_),
    .A2(_0330_),
    .B(_0331_),
    .ZN(_0096_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _0739_ (
    .A1(\signal_gen.mix.mixout[3] ),
    .A2(_0152_),
    .B1(\signal_gen.mix.mixout[2] ),
    .B2(_0153_),
    .ZN(_0332_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai22_1 _0740_ (
    .A1(\signal_gen.mix.mixout[4] ),
    .A2(_0151_),
    .B1(\signal_gen.mix.mixout[3] ),
    .B2(_0152_),
    .ZN(_0333_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _0741_ (
    .A1(\signal_gen.mix.mixout[4] ),
    .A2(_0151_),
    .ZN(_0334_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai221_1 _0742_ (
    .A1(_0150_),
    .A2(\signal_gen.pwm.clk_cnt[5] ),
    .B1(_0332_),
    .B2(_0333_),
    .C(_0334_),
    .ZN(_0335_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _0743_ (
    .A1(_0149_),
    .A2(\signal_gen.pwm.clk_cnt[6] ),
    .B1(_0150_),
    .B2(\signal_gen.pwm.clk_cnt[5] ),
    .ZN(_0336_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _0744_ (
    .A1(_0149_),
    .A2(\signal_gen.pwm.clk_cnt[6] ),
    .ZN(_0337_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi221_1 _0745_ (
    .A1(\signal_gen.mix.mixout[7] ),
    .A2(_0148_),
    .B1(_0335_),
    .B2(_0336_),
    .C(_0337_),
    .ZN(_0338_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _0746_ (
    .A1(\signal_gen.mix.mixout[7] ),
    .A2(_0148_),
    .B(rst_n),
    .ZN(_0339_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _0747_ (
    .A1(_0338_),
    .A2(_0339_),
    .ZN(_0097_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _0748_ (
    .A1(_0269_),
    .A2(_0277_),
    .ZN(_0340_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _0749_ (
    .A1(\signal_gen.envA_gen.timer[0] ),
    .A2(_0277_),
    .Z(_0341_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _0750_ (
    .A1(_0340_),
    .A2(_0341_),
    .ZN(_0098_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _0751_ (
    .A1(\signal_gen.envA_gen.timer[0] ),
    .A2(_0278_),
    .B(\signal_gen.envA_gen.timer[1] ),
    .ZN(_0342_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _0752_ (
    .A1(_0340_),
    .A2(_0342_),
    .ZN(_0099_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _0753_ (
    .A1(\signal_gen.envA_gen.timer[2] ),
    .A2(_0277_),
    .Z(_0100_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _0754_ (
    .A1(\signal_gen.envA_gen.timer[3] ),
    .A2(_0277_),
    .Z(_0101_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _0755_ (
    .A1(\signal_gen.envA[2] ),
    .A2(\signal_gen.volA[2] ),
    .ZN(_0343_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _0756_ (
    .A1(\signal_gen.envA[2] ),
    .A2(\signal_gen.volA[2] ),
    .Z(_0344_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand4_1 _0757_ (
    .A1(\signal_gen.envA[0] ),
    .A2(\signal_gen.envA[1] ),
    .A3(\signal_gen.volA[1] ),
    .A4(\signal_gen.volA[0] ),
    .ZN(_0345_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _0758_ (
    .A1(\signal_gen.envA[3] ),
    .A2(\signal_gen.volA[0] ),
    .ZN(_0346_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _0759_ (
    .A1(\signal_gen.envA[2] ),
    .A2(\signal_gen.volA[1] ),
    .ZN(_0347_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _0760_ (
    .A1(\signal_gen.envA[0] ),
    .A2(\signal_gen.volA[3] ),
    .ZN(_0348_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _0761_ (
    .A1(\signal_gen.envA[1] ),
    .A2(\signal_gen.volA[2] ),
    .ZN(_0349_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _0762_ (
    .A1(\signal_gen.envA[0] ),
    .A2(\signal_gen.volA[3] ),
    .B1(\signal_gen.volA[2] ),
    .B2(\signal_gen.envA[1] ),
    .ZN(_0350_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _0763_ (
    .A1(\signal_gen.envA[0] ),
    .A2(\signal_gen.volA[2] ),
    .ZN(_0351_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _0764_ (
    .A1(\signal_gen.envA[1] ),
    .A2(\signal_gen.volA[3] ),
    .ZN(_0352_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xnor3_1 _0765_ (
    .A1(_0347_),
    .A2(_0348_),
    .A3(_0349_),
    .ZN(_0353_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _0766_ (
    .A1(\signal_gen.envA[1] ),
    .A2(\signal_gen.volA[1] ),
    .B1(\signal_gen.volA[0] ),
    .B2(\signal_gen.envA[2] ),
    .ZN(_0354_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand4_1 _0767_ (
    .A1(\signal_gen.envA[1] ),
    .A2(\signal_gen.envA[2] ),
    .A3(\signal_gen.volA[1] ),
    .A4(\signal_gen.volA[0] ),
    .ZN(_0355_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _0768_ (
    .A1(_0351_),
    .A2(_0355_),
    .B(_0354_),
    .ZN(_0356_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _0769_ (
    .A1(_0353_),
    .A2(_0356_),
    .ZN(_0357_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _0770_ (
    .A1(_0353_),
    .A2(_0356_),
    .ZN(_0358_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _0771_ (
    .A1(_0353_),
    .A2(_0356_),
    .Z(_0359_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _0772_ (
    .A1(\signal_gen.envA[3] ),
    .A2(\signal_gen.volA[0] ),
    .A3(_0359_),
    .ZN(_0360_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _0773_ (
    .A1(_0346_),
    .A2(_0359_),
    .Z(_0361_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _0774_ (
    .A1(_0344_),
    .A2(_0345_),
    .A3(_0361_),
    .ZN(_0362_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _0775_ (
    .A1(_0344_),
    .A2(_0345_),
    .B(_0361_),
    .ZN(_0363_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _0776_ (
    .A1(_0209_),
    .A2(_0362_),
    .ZN(_0364_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _0777_ (
    .A1(\signal_gen.mix.multA[3] ),
    .A2(_0207_),
    .B1(_0363_),
    .B2(_0364_),
    .ZN(_0365_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _0778_ (
    .I(_0365_),
    .ZN(_0102_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _0779_ (
    .A1(\signal_gen.envA[3] ),
    .A2(\signal_gen.volA[1] ),
    .ZN(_0366_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai22_1 _0780_ (
    .A1(_0347_),
    .A2(_0350_),
    .B1(_0351_),
    .B2(_0352_),
    .ZN(_0367_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _0781_ (
    .A1(\signal_gen.envA[2] ),
    .A2(\signal_gen.volA[3] ),
    .Z(_0368_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _0782_ (
    .A1(_0343_),
    .A2(_0352_),
    .Z(_0369_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _0783_ (
    .A1(_0367_),
    .A2(_0369_),
    .ZN(_0370_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _0784_ (
    .A1(_0367_),
    .A2(_0369_),
    .Z(_0371_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _0785_ (
    .A1(\signal_gen.envA[3] ),
    .A2(\signal_gen.volA[1] ),
    .A3(_0371_),
    .ZN(_0372_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _0786_ (
    .A1(_0366_),
    .A2(_0371_),
    .Z(_0373_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _0787_ (
    .A1(_0346_),
    .A2(_0358_),
    .B(_0357_),
    .ZN(_0374_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _0788_ (
    .A1(_0357_),
    .A2(_0360_),
    .B(_0373_),
    .ZN(_0375_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xnor2_1 _0789_ (
    .A1(_0373_),
    .A2(_0374_),
    .ZN(_0376_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _0790_ (
    .A1(_0362_),
    .A2(_0376_),
    .Z(_0377_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _0791_ (
    .A1(\signal_gen.mix.multA[4] ),
    .A2(_0207_),
    .B1(_0208_),
    .B2(_0377_),
    .ZN(_0378_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _0792_ (
    .I(_0378_),
    .ZN(_0103_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _0793_ (
    .A1(\signal_gen.mix.multA[5] ),
    .A2(_0207_),
    .ZN(_0379_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _0794_ (
    .A1(_0349_),
    .A2(_0368_),
    .ZN(_0380_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _0795_ (
    .A1(\signal_gen.envA[3] ),
    .A2(\signal_gen.volA[2] ),
    .ZN(_0381_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xnor2_1 _0796_ (
    .A1(_0380_),
    .A2(_0381_),
    .ZN(_0382_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _0797_ (
    .A1(_0370_),
    .A2(_0372_),
    .ZN(_0383_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _0798_ (
    .A1(_0370_),
    .A2(_0372_),
    .B(_0382_),
    .ZN(_0384_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _0799_ (
    .A1(_0370_),
    .A2(_0372_),
    .A3(_0382_),
    .ZN(_0385_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _0800_ (
    .A1(_0362_),
    .A2(_0376_),
    .B(_0375_),
    .ZN(_0386_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xnor3_1 _0801_ (
    .A1(_0382_),
    .A2(_0383_),
    .A3(_0386_),
    .ZN(_0387_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _0802_ (
    .A1(_0209_),
    .A2(_0387_),
    .B(_0379_),
    .ZN(_0104_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _0803_ (
    .A1(\signal_gen.mix.multA[6] ),
    .A2(_0207_),
    .ZN(_0388_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _0804_ (
    .A1(\signal_gen.envA[3] ),
    .A2(\signal_gen.volA[3] ),
    .ZN(_0389_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand4_1 _0805_ (
    .A1(\signal_gen.envA[3] ),
    .A2(\signal_gen.volA[3] ),
    .A3(\signal_gen.volA[2] ),
    .A4(_0368_),
    .ZN(_0390_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai221_1 _0806_ (
    .A1(_0343_),
    .A2(_0352_),
    .B1(_0380_),
    .B2(_0381_),
    .C(_0389_),
    .ZN(_0391_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _0807_ (
    .A1(_0390_),
    .A2(_0391_),
    .ZN(_0392_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _0808_ (
    .A1(_0375_),
    .A2(_0385_),
    .B(_0384_),
    .ZN(_0393_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _0809_ (
    .A1(_0392_),
    .A2(_0393_),
    .ZN(_0394_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _0810_ (
    .A1(_0392_),
    .A2(_0393_),
    .Z(_0395_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai31_1 _0811_ (
    .A1(_0209_),
    .A2(_0394_),
    .A3(_0395_),
    .B(_0388_),
    .ZN(_0105_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai211_1 _0812_ (
    .A1(_0392_),
    .A2(_0393_),
    .B(\signal_gen.mix.started ),
    .C(_0390_),
    .ZN(_0396_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or2_1 _0813_ (
    .A1(\signal_gen.mix.started ),
    .A2(\signal_gen.mix.multA[7] ),
    .Z(_0397_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and3_1 _0814_ (
    .A1(rst_n),
    .A2(_0396_),
    .A3(_0397_),
    .Z(_0106_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and3_1 _0815_ (
    .A1(\signal_gen.enableA ),
    .A2(\signal_gen.mix.waveA ),
    .A3(_0208_),
    .Z(_0398_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _0816_ (
    .A1(\signal_gen.mix.a_val[0] ),
    .A2(_0207_),
    .B1(_0398_),
    .B2(\signal_gen.mix.multA[3] ),
    .ZN(_0399_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _0817_ (
    .I(_0399_),
    .ZN(_0107_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _0818_ (
    .A1(\signal_gen.mix.a_val[1] ),
    .A2(_0207_),
    .B1(_0398_),
    .B2(\signal_gen.mix.multA[4] ),
    .ZN(_0400_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _0819_ (
    .I(_0400_),
    .ZN(_0108_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _0820_ (
    .A1(\signal_gen.mix.a_val[2] ),
    .A2(_0207_),
    .B1(_0398_),
    .B2(\signal_gen.mix.multA[5] ),
    .ZN(_0401_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _0821_ (
    .I(_0401_),
    .ZN(_0109_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _0822_ (
    .A1(\signal_gen.mix.a_val[3] ),
    .A2(_0207_),
    .B1(_0398_),
    .B2(\signal_gen.mix.multA[6] ),
    .ZN(_0402_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _0823_ (
    .I(_0402_),
    .ZN(_0110_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _0824_ (
    .A1(\signal_gen.mix.a_val[4] ),
    .A2(_0207_),
    .B1(_0398_),
    .B2(\signal_gen.mix.multA[7] ),
    .ZN(_0403_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _0825_ (
    .I(_0403_),
    .ZN(_0111_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _0826_ (
    .A1(\signal_gen.mix.sum[0] ),
    .A2(_0207_),
    .B1(_0208_),
    .B2(\signal_gen.mix.a_val[0] ),
    .ZN(_0404_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _0827_ (
    .I(_0404_),
    .ZN(_0112_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _0828_ (
    .A1(\signal_gen.mix.a_val[1] ),
    .A2(\signal_gen.mix.n_val[1] ),
    .ZN(_0405_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _0829_ (
    .A1(\signal_gen.mix.a_val[1] ),
    .A2(\signal_gen.mix.n_val[1] ),
    .Z(_0406_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _0830_ (
    .A1(\signal_gen.mix.sum[1] ),
    .A2(_0207_),
    .B1(_0208_),
    .B2(_0406_),
    .ZN(_0407_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _0831_ (
    .I(_0407_),
    .ZN(_0113_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _0832_ (
    .A1(\signal_gen.mix.sum[2] ),
    .A2(_0207_),
    .ZN(_0408_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _0833_ (
    .A1(\signal_gen.mix.a_val[2] ),
    .A2(\signal_gen.mix.n_val[2] ),
    .ZN(_0409_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _0834_ (
    .A1(\signal_gen.mix.a_val[2] ),
    .A2(\signal_gen.mix.n_val[2] ),
    .ZN(_0410_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor3_1 _0835_ (
    .A1(\signal_gen.mix.a_val[2] ),
    .A2(\signal_gen.mix.n_val[2] ),
    .A3(_0405_),
    .Z(_0411_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _0836_ (
    .A1(_0209_),
    .A2(_0411_),
    .B(_0408_),
    .ZN(_0114_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _0837_ (
    .A1(\signal_gen.mix.a_val[3] ),
    .A2(\signal_gen.mix.n_val[3] ),
    .ZN(_0412_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _0838_ (
    .I(_0412_),
    .ZN(_0413_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _0839_ (
    .A1(\signal_gen.mix.a_val[3] ),
    .A2(\signal_gen.mix.n_val[3] ),
    .Z(_0414_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _0840_ (
    .A1(_0405_),
    .A2(_0410_),
    .B(_0409_),
    .ZN(_0415_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _0841_ (
    .A1(_0414_),
    .A2(_0415_),
    .Z(_0416_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _0842_ (
    .A1(_0414_),
    .A2(_0415_),
    .Z(_0417_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _0843_ (
    .I0(\signal_gen.mix.sum[3] ),
    .I1(_0417_),
    .S(\signal_gen.mix.started ),
    .Z(_0418_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _0844_ (
    .A1(rst_n),
    .A2(_0418_),
    .ZN(_0419_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _0845_ (
    .I(_0419_),
    .ZN(_0115_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _0846_ (
    .A1(\signal_gen.mix.sum[4] ),
    .A2(_0207_),
    .ZN(_0420_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _0847_ (
    .A1(\signal_gen.mix.a_val[4] ),
    .A2(\signal_gen.mix.n_val[4] ),
    .Z(_0421_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _0848_ (
    .A1(\signal_gen.mix.a_val[4] ),
    .A2(\signal_gen.mix.n_val[4] ),
    .Z(_0422_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _0849_ (
    .A1(_0413_),
    .A2(_0416_),
    .A3(_0422_),
    .ZN(_0423_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _0850_ (
    .A1(_0413_),
    .A2(_0416_),
    .B(_0422_),
    .ZN(_0424_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _0851_ (
    .A1(_0208_),
    .A2(_0424_),
    .ZN(_0425_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _0852_ (
    .A1(_0423_),
    .A2(_0425_),
    .B(_0420_),
    .ZN(_0116_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _0853_ (
    .A1(\signal_gen.mix.started ),
    .A2(_0424_),
    .ZN(_0426_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai221_1 _0854_ (
    .A1(\signal_gen.mix.sum[5] ),
    .A2(\signal_gen.mix.started ),
    .B1(_0421_),
    .B2(_0426_),
    .C(rst_n),
    .ZN(_0427_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _0855_ (
    .I(_0427_),
    .ZN(_0117_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _0856_ (
    .A1(\signal_gen.enableN ),
    .A2(\signal_gen.n.feedback ),
    .ZN(_0428_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai211_1 _0857_ (
    .A1(\signal_gen.enableN ),
    .A2(_0125_),
    .B(rst_n),
    .C(_0428_),
    .ZN(_0118_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _0858_ (
    .A1(\signal_gen.enableN ),
    .A2(\signal_gen.n.noise_reg[1] ),
    .B(rst_n),
    .ZN(_0429_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _0859_ (
    .A1(\signal_gen.enableN ),
    .A2(_0125_),
    .B(_0429_),
    .ZN(_0119_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _0860_ (
    .A1(\signal_gen.n.noise_reg[2] ),
    .A2(\signal_gen.enableN ),
    .B(rst_n),
    .ZN(_0430_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _0861_ (
    .A1(\signal_gen.enableN ),
    .A2(_0124_),
    .B(_0430_),
    .ZN(_0120_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _0862_ (
    .A1(\signal_gen.n.noise_reg[3] ),
    .A2(\signal_gen.enableN ),
    .B(rst_n),
    .ZN(_0431_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _0863_ (
    .A1(_0123_),
    .A2(\signal_gen.enableN ),
    .B(_0431_),
    .ZN(_0121_)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0864_ (
    .CLK(clk_scaled),
    .D(_0012_),
    .Q(\signal_gen.n.noise_reg[4] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0865_ (
    .CLK(clk_scaled),
    .D(_0013_),
    .Q(\signal_gen.n.noise_reg[5] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0866_ (
    .CLK(clk_scaled),
    .D(_0014_),
    .Q(\signal_gen.n.noise_reg[6] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0867_ (
    .CLK(clk_scaled),
    .D(_0015_),
    .Q(\signal_gen.n.noise_reg[7] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0868_ (
    .CLK(clk_scaled),
    .D(_0016_),
    .Q(\signal_gen.n.noise_reg[8] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0869_ (
    .CLK(clk_scaled),
    .D(_0017_),
    .Q(\signal_gen.n.noise_reg[9] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0870_ (
    .CLK(clk_scaled),
    .D(_0018_),
    .Q(\signal_gen.n.noise_reg[10] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0871_ (
    .CLK(clk_scaled),
    .D(_0019_),
    .Q(\signal_gen.n.noise_reg[11] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0872_ (
    .CLK(clk_scaled),
    .D(_0020_),
    .Q(\signal_gen.n.noise_reg[12] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0873_ (
    .CLK(clk_scaled),
    .D(_0021_),
    .Q(\signal_gen.n.noise_reg[13] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0874_ (
    .CLK(clk_scaled),
    .D(\signal_gen.n.noise_reg[0] ),
    .Q(\signal_gen.n.noise_out )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0875_ (
    .CLK(clk_scaled),
    .D(_0022_),
    .Q(\signal_gen.vib_depth[0] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0876_ (
    .CLK(clk_scaled),
    .D(_0023_),
    .Q(\signal_gen.vib_depth[1] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0877_ (
    .CLK(clk_scaled),
    .D(_0024_),
    .Q(\signal_gen.vib_depth[2] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0878_ (
    .CLK(clk_scaled),
    .D(_0025_),
    .Q(\signal_gen.vib_depth[3] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0879_ (
    .CLK(clk_scaled),
    .D(_0026_),
    .Q(\signal_gen.mix.n_val[1] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0880_ (
    .CLK(clk_scaled),
    .D(_0027_),
    .Q(\signal_gen.mix.n_val[2] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0881_ (
    .CLK(clk_scaled),
    .D(_0028_),
    .Q(\signal_gen.mix.n_val[3] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0882_ (
    .CLK(clk_scaled),
    .D(_0029_),
    .Q(\signal_gen.mix.n_val[4] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _0883_ (
    .CLK(clk_scaled),
    .D(_0000_),
    .Q(\signal_gen.tA.cnt[0] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _0884_ (
    .CLK(clk_scaled),
    .D(_0003_),
    .Q(\signal_gen.tA.cnt[1] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _0885_ (
    .CLK(clk_scaled),
    .D(_0004_),
    .Q(\signal_gen.tA.cnt[2] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _0886_ (
    .CLK(clk_scaled),
    .D(_0005_),
    .Q(\signal_gen.tA.cnt[3] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _0887_ (
    .CLK(clk_scaled),
    .D(_0006_),
    .Q(\signal_gen.tA.cnt[4] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _0888_ (
    .CLK(clk_scaled),
    .D(_0007_),
    .Q(\signal_gen.tA.cnt[5] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _0889_ (
    .CLK(clk_scaled),
    .D(_0008_),
    .Q(\signal_gen.tA.cnt[6] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _0890_ (
    .CLK(clk_scaled),
    .D(_0009_),
    .Q(\signal_gen.tA.cnt[7] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _0891_ (
    .CLK(clk_scaled),
    .D(_0010_),
    .Q(\signal_gen.tA.cnt[8] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _0892_ (
    .CLK(clk_scaled),
    .D(_0011_),
    .Q(\signal_gen.tA.cnt[9] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _0893_ (
    .CLK(clk_scaled),
    .D(_0001_),
    .Q(\signal_gen.tA.cnt[10] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _0894_ (
    .CLK(clk_scaled),
    .D(_0002_),
    .Q(\signal_gen.tA.cnt[11] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0895_ (
    .CLK(clk_scaled),
    .D(_0030_),
    .Q(\signal_gen.pwm.clk_cnt[0] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0896_ (
    .CLK(clk_scaled),
    .D(_0031_),
    .Q(\signal_gen.pwm.clk_cnt[1] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0897_ (
    .CLK(clk_scaled),
    .D(_0032_),
    .Q(\signal_gen.pwm.clk_cnt[2] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0898_ (
    .CLK(clk_scaled),
    .D(_0033_),
    .Q(\signal_gen.pwm.clk_cnt[3] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0899_ (
    .CLK(clk_scaled),
    .D(_0034_),
    .Q(\signal_gen.pwm.clk_cnt[4] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0900_ (
    .CLK(clk_scaled),
    .D(_0035_),
    .Q(\signal_gen.pwm.clk_cnt[5] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0901_ (
    .CLK(clk_scaled),
    .D(_0036_),
    .Q(\signal_gen.pwm.clk_cnt[6] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0902_ (
    .CLK(clk_scaled),
    .D(_0037_),
    .Q(\signal_gen.pwm.clk_cnt[7] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0903_ (
    .CLK(clk_scaled),
    .D(_0038_),
    .Q(\signal_gen.vibA[0] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0904_ (
    .CLK(clk_scaled),
    .D(_0039_),
    .Q(\signal_gen.vibA[1] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0905_ (
    .CLK(clk_scaled),
    .D(_0040_),
    .Q(\signal_gen.vibA[2] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0906_ (
    .CLK(clk_scaled),
    .D(_0041_),
    .Q(\signal_gen.vibA[3] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _0907_ (
    .CLK(clk_scaled),
    .D(_0042_),
    .Q(\signal_gen.mix.waveA ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0908_ (
    .CLK(clk_scaled),
    .D(_0043_),
    .Q(\signal_gen.vibA_gen.dir )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0909_ (
    .CLK(clk_scaled),
    .D(_0044_),
    .Q(\signal_gen.vibA_gen.val[0] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0910_ (
    .CLK(clk_scaled),
    .D(_0045_),
    .Q(\signal_gen.vibA_gen.val[1] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0911_ (
    .CLK(clk_scaled),
    .D(_0046_),
    .Q(\signal_gen.vibA_gen.val[2] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0912_ (
    .CLK(clk_scaled),
    .D(_0047_),
    .Q(\signal_gen.vibA_gen.val[3] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0913_ (
    .CLK(clk_scaled),
    .D(_0048_),
    .Q(\signal_gen.enableVib )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0914_ (
    .CLK(clk_scaled),
    .D(_0049_),
    .Q(\signal_gen.enableN )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0915_ (
    .CLK(clk_scaled),
    .D(_0050_),
    .Q(\signal_gen.enableA )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0916_ (
    .CLK(clk_scaled),
    .D(_0051_),
    .Q(\signal_gen.volN[0] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0917_ (
    .CLK(clk_scaled),
    .D(_0052_),
    .Q(\signal_gen.volN[1] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0918_ (
    .CLK(clk_scaled),
    .D(_0053_),
    .Q(\signal_gen.volN[2] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0919_ (
    .CLK(clk_scaled),
    .D(_0054_),
    .Q(\signal_gen.volN[3] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0920_ (
    .CLK(clk_scaled),
    .D(_0055_),
    .Q(\signal_gen.volA[0] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0921_ (
    .CLK(clk_scaled),
    .D(_0056_),
    .Q(\signal_gen.volA[1] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0922_ (
    .CLK(clk_scaled),
    .D(_0057_),
    .Q(\signal_gen.volA[2] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0923_ (
    .CLK(clk_scaled),
    .D(_0058_),
    .Q(\signal_gen.volA[3] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0924_ (
    .CLK(clk_scaled),
    .D(_0059_),
    .Q(\signal_gen.periodA[0] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0925_ (
    .CLK(clk_scaled),
    .D(_0060_),
    .Q(\signal_gen.periodA[1] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0926_ (
    .CLK(clk_scaled),
    .D(_0061_),
    .Q(\signal_gen.periodA[2] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0927_ (
    .CLK(clk_scaled),
    .D(_0062_),
    .Q(\signal_gen.periodA[3] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0928_ (
    .CLK(clk_scaled),
    .D(_0063_),
    .Q(\signal_gen.periodA[4] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0929_ (
    .CLK(clk_scaled),
    .D(_0064_),
    .Q(\signal_gen.envA_gen.state[1] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0930_ (
    .CLK(clk_scaled),
    .D(_0065_),
    .Q(\signal_gen.envA_gen.state[0] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0931_ (
    .CLK(clk),
    .D(_0066_),
    .Q(\clk_scaler.counter[0] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0932_ (
    .CLK(clk),
    .D(_0067_),
    .Q(\clk_scaler.counter[1] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0933_ (
    .CLK(clk),
    .D(_0068_),
    .Q(\clk_scaler.counter[2] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0934_ (
    .CLK(clk),
    .D(_0069_),
    .Q(\clk_scaler.counter[3] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0935_ (
    .CLK(clk),
    .D(_0070_),
    .Q(\clk_scaler.counter[4] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0936_ (
    .CLK(clk),
    .D(_0071_),
    .Q(\clk_scaler.counter[5] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0937_ (
    .CLK(clk),
    .D(_0072_),
    .Q(\clk_scaler.counter[6] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0938_ (
    .CLK(clk),
    .D(_0073_),
    .Q(\clk_scaler.counter[7] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0939_ (
    .CLK(clk),
    .D(_0074_),
    .Q(\clk_scaler.counter[8] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0940_ (
    .CLK(clk),
    .D(_0075_),
    .Q(\clk_scaler.counter[9] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0941_ (
    .CLK(clk),
    .D(_0076_),
    .Q(\clk_scaler.counter[10] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0942_ (
    .CLK(clk),
    .D(_0077_),
    .Q(clk_scaled)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0943_ (
    .CLK(clk_scaled),
    .D(_0078_),
    .Q(\signal_gen.envA[0] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0944_ (
    .CLK(clk_scaled),
    .D(_0079_),
    .Q(\signal_gen.envA[1] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0945_ (
    .CLK(clk_scaled),
    .D(_0080_),
    .Q(\signal_gen.envA[2] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0946_ (
    .CLK(clk_scaled),
    .D(_0081_),
    .Q(\signal_gen.envA[3] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0947_ (
    .CLK(clk_scaled),
    .D(_0082_),
    .Q(\signal_gen.mix.mixout[2] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0948_ (
    .CLK(clk_scaled),
    .D(_0083_),
    .Q(\signal_gen.mix.mixout[3] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0949_ (
    .CLK(clk_scaled),
    .D(_0084_),
    .Q(\signal_gen.mix.mixout[4] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0950_ (
    .CLK(clk_scaled),
    .D(_0085_),
    .Q(\signal_gen.mix.mixout[5] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0951_ (
    .CLK(clk_scaled),
    .D(_0086_),
    .Q(\signal_gen.mix.mixout[6] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0952_ (
    .CLK(clk_scaled),
    .D(_0087_),
    .Q(\signal_gen.mix.mixout[7] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0953_ (
    .CLK(clk_scaled),
    .D(_0088_),
    .Q(\signal_gen.vibA_gen.div[0] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0954_ (
    .CLK(clk_scaled),
    .D(_0089_),
    .Q(\signal_gen.vibA_gen.div[1] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0955_ (
    .CLK(clk_scaled),
    .D(_0090_),
    .Q(\signal_gen.vibA_gen.div[2] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0956_ (
    .CLK(clk_scaled),
    .D(_0091_),
    .Q(\signal_gen.vibA_gen.div[3] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0957_ (
    .CLK(clk_scaled),
    .D(_0092_),
    .Q(\signal_gen.vibA_gen.div[4] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0958_ (
    .CLK(clk_scaled),
    .D(_0093_),
    .Q(\signal_gen.vibA_gen.div[5] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0959_ (
    .CLK(clk_scaled),
    .D(_0094_),
    .Q(\signal_gen.vibA_gen.div[6] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0960_ (
    .CLK(clk_scaled),
    .D(_0095_),
    .Q(\signal_gen.vibA_gen.div[7] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0961_ (
    .CLK(clk_scaled),
    .D(_0096_),
    .Q(\signal_gen.n.feedback )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0962_ (
    .CLK(clk_scaled),
    .D(_0097_),
    .Q(\signal_gen.pwm.pwm_o )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0963_ (
    .CLK(clk_scaled),
    .D(_0098_),
    .Q(\signal_gen.envA_gen.timer[0] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0964_ (
    .CLK(clk_scaled),
    .D(_0099_),
    .Q(\signal_gen.envA_gen.timer[1] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0965_ (
    .CLK(clk_scaled),
    .D(_0100_),
    .Q(\signal_gen.envA_gen.timer[2] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0966_ (
    .CLK(clk_scaled),
    .D(_0101_),
    .Q(\signal_gen.envA_gen.timer[3] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0967_ (
    .CLK(clk_scaled),
    .D(_0102_),
    .Q(\signal_gen.mix.multA[3] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0968_ (
    .CLK(clk_scaled),
    .D(_0103_),
    .Q(\signal_gen.mix.multA[4] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0969_ (
    .CLK(clk_scaled),
    .D(_0104_),
    .Q(\signal_gen.mix.multA[5] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0970_ (
    .CLK(clk_scaled),
    .D(_0105_),
    .Q(\signal_gen.mix.multA[6] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0971_ (
    .CLK(clk_scaled),
    .D(_0106_),
    .Q(\signal_gen.mix.multA[7] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0972_ (
    .CLK(clk_scaled),
    .D(_0107_),
    .Q(\signal_gen.mix.a_val[0] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0973_ (
    .CLK(clk_scaled),
    .D(_0108_),
    .Q(\signal_gen.mix.a_val[1] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0974_ (
    .CLK(clk_scaled),
    .D(_0109_),
    .Q(\signal_gen.mix.a_val[2] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0975_ (
    .CLK(clk_scaled),
    .D(_0110_),
    .Q(\signal_gen.mix.a_val[3] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0976_ (
    .CLK(clk_scaled),
    .D(_0111_),
    .Q(\signal_gen.mix.a_val[4] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0977_ (
    .CLK(clk_scaled),
    .D(_0112_),
    .Q(\signal_gen.mix.sum[0] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0978_ (
    .CLK(clk_scaled),
    .D(_0113_),
    .Q(\signal_gen.mix.sum[1] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0979_ (
    .CLK(clk_scaled),
    .D(_0114_),
    .Q(\signal_gen.mix.sum[2] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0980_ (
    .CLK(clk_scaled),
    .D(_0115_),
    .Q(\signal_gen.mix.sum[3] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0981_ (
    .CLK(clk_scaled),
    .D(_0116_),
    .Q(\signal_gen.mix.sum[4] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0982_ (
    .CLK(clk_scaled),
    .D(_0117_),
    .Q(\signal_gen.mix.sum[5] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0983_ (
    .CLK(clk_scaled),
    .D(rst_n),
    .Q(\signal_gen.mix.started )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0984_ (
    .CLK(clk_scaled),
    .D(_0118_),
    .Q(\signal_gen.n.noise_reg[0] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0985_ (
    .CLK(clk_scaled),
    .D(_0119_),
    .Q(\signal_gen.n.noise_reg[1] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0986_ (
    .CLK(clk_scaled),
    .D(_0120_),
    .Q(\signal_gen.n.noise_reg[2] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _0987_ (
    .CLK(clk_scaled),
    .D(_0121_),
    .Q(\signal_gen.n.noise_reg[3] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tieh _0988_ (
    .Z(uio_oe[0])
  );
  gf180mcu_fd_sc_mcu7t5v0__tieh _0989_ (
    .Z(uio_oe[1])
  );
  gf180mcu_fd_sc_mcu7t5v0__tieh _0990_ (
    .Z(uio_oe[2])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _0991_ (
    .ZN(uio_oe[3])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _0992_ (
    .ZN(uio_oe[4])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _0993_ (
    .ZN(uio_oe[5])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _0994_ (
    .ZN(uio_oe[6])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _0995_ (
    .ZN(uio_oe[7])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _0996_ (
    .ZN(uio_out[0])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _0997_ (
    .ZN(uio_out[1])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _0998_ (
    .ZN(uio_out[2])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _0999_ (
    .ZN(uio_out[3])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _1000_ (
    .ZN(uio_out[4])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _1001_ (
    .ZN(uio_out[5])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _1002_ (
    .ZN(uio_out[6])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _1003_ (
    .ZN(uio_out[7])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _1004_ (
    .ZN(uo_out[1])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _1005_ (
    .ZN(uo_out[2])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _1006_ (
    .ZN(uo_out[3])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _1007_ (
    .ZN(uo_out[4])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _1008_ (
    .ZN(uo_out[5])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _1009_ (
    .ZN(uo_out[6])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _1010_ (
    .ZN(uo_out[7])
  );
  gf180mcu_fd_sc_mcu7t5v0__buf_1 _1011_ (
    .I(\signal_gen.pwm.pwm_o ),
    .Z(uo_out[0])
  );
endmodule
