/* Generated by Yosys 0.57 (git sha1 3aca86049, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

module tiny_tonegen(clk, rst_n, ena, address_in, write_strobe_in, data_in, signal_bit_out);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input ena;
  wire ena;
  input [2:0] address_in;
  wire [2:0] address_in;
  input write_strobe_in;
  wire write_strobe_in;
  input [4:0] data_in;
  wire [4:0] data_in;
  output signal_bit_out;
  wire signal_bit_out;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire clk_scaled;
  wire \clk_scaler.counter[0] ;
  wire \clk_scaler.counter[1] ;
  wire \clk_scaler.counter[2] ;
  wire \clk_scaler.counter[3] ;
  wire \clk_scaler.counter[4] ;
  wire \clk_scaler.counter[5] ;
  wire \clk_scaler.counter[6] ;
  wire \clk_scaler.counter[7] ;
  wire \signal_gen.enableA ;
  wire \signal_gen.enableN ;
  wire \signal_gen.envA[0] ;
  wire \signal_gen.envA[1] ;
  wire \signal_gen.envA[2] ;
  wire \signal_gen.envA[3] ;
  wire \signal_gen.envA_gen.state[0] ;
  wire \signal_gen.envA_gen.state[1] ;
  wire \signal_gen.envA_gen.timer[0] ;
  wire \signal_gen.envA_gen.timer[1] ;
  wire \signal_gen.envA_gen.timer[2] ;
  wire \signal_gen.envA_gen.timer[3] ;
  wire \signal_gen.mix.a_val[0] ;
  wire \signal_gen.mix.a_val[1] ;
  wire \signal_gen.mix.a_val[2] ;
  wire \signal_gen.mix.a_val[3] ;
  wire \signal_gen.mix.a_val[4] ;
  wire \signal_gen.mix.mixout[2] ;
  wire \signal_gen.mix.mixout[3] ;
  wire \signal_gen.mix.mixout[4] ;
  wire \signal_gen.mix.mixout[5] ;
  wire \signal_gen.mix.mixout[6] ;
  wire \signal_gen.mix.mixout[7] ;
  wire \signal_gen.mix.n_val[1] ;
  wire \signal_gen.mix.n_val[2] ;
  wire \signal_gen.mix.n_val[3] ;
  wire \signal_gen.mix.n_val[4] ;
  wire \signal_gen.mix.noise ;
  wire \signal_gen.mix.started ;
  wire \signal_gen.mix.sum[0] ;
  wire \signal_gen.mix.sum[1] ;
  wire \signal_gen.mix.sum[2] ;
  wire \signal_gen.mix.sum[3] ;
  wire \signal_gen.mix.sum[4] ;
  wire \signal_gen.mix.sum[5] ;
  wire \signal_gen.mix.waveA ;
  wire \signal_gen.noise_gen.feedback ;
  wire \signal_gen.noise_gen.noise_reg[0] ;
  wire \signal_gen.noise_gen.noise_reg[10] ;
  wire \signal_gen.noise_gen.noise_reg[11] ;
  wire \signal_gen.noise_gen.noise_reg[12] ;
  wire \signal_gen.noise_gen.noise_reg[13] ;
  wire \signal_gen.noise_gen.noise_reg[2] ;
  wire \signal_gen.noise_gen.noise_reg[3] ;
  wire \signal_gen.noise_gen.noise_reg[4] ;
  wire \signal_gen.noise_gen.noise_reg[5] ;
  wire \signal_gen.noise_gen.noise_reg[6] ;
  wire \signal_gen.noise_gen.noise_reg[7] ;
  wire \signal_gen.noise_gen.noise_reg[8] ;
  wire \signal_gen.noise_gen.noise_reg[9] ;
  wire \signal_gen.periodA[0] ;
  wire \signal_gen.periodA[1] ;
  wire \signal_gen.periodA[2] ;
  wire \signal_gen.periodA[3] ;
  wire \signal_gen.periodA[4] ;
  wire \signal_gen.pwmGen.clk_cnt[0] ;
  wire \signal_gen.pwmGen.clk_cnt[1] ;
  wire \signal_gen.pwmGen.clk_cnt[2] ;
  wire \signal_gen.pwmGen.clk_cnt[3] ;
  wire \signal_gen.pwmGen.clk_cnt[4] ;
  wire \signal_gen.pwmGen.clk_cnt[5] ;
  wire \signal_gen.pwmGen.clk_cnt[6] ;
  wire \signal_gen.pwmGen.clk_cnt[7] ;
  wire \signal_gen.tonegenA.counter[0] ;
  wire \signal_gen.tonegenA.counter[1] ;
  wire \signal_gen.tonegenA.counter[2] ;
  wire \signal_gen.tonegenA.counter[3] ;
  wire \signal_gen.tonegenA.counter[4] ;
  wire \signal_gen.tonegenA.counter[5] ;
  wire \signal_gen.tonegenA.counter[6] ;
  wire \signal_gen.tonegenA.counter[7] ;
  wire \signal_gen.volA[0] ;
  wire \signal_gen.volA[1] ;
  wire \signal_gen.volA[2] ;
  wire \signal_gen.volA[3] ;
  wire \signal_gen.volN[0] ;
  wire \signal_gen.volN[1] ;
  wire \signal_gen.volN[2] ;
  wire \signal_gen.volN[3] ;
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _314_ (
    .I(\signal_gen.periodA[1] ),
    .ZN(_102_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _315_ (
    .I(\signal_gen.volA[3] ),
    .ZN(_103_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _316_ (
    .I(\signal_gen.envA_gen.timer[1] ),
    .ZN(_104_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _317_ (
    .I(\signal_gen.envA_gen.state[1] ),
    .ZN(_105_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _318_ (
    .I(\signal_gen.envA[3] ),
    .ZN(_106_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _319_ (
    .I(\signal_gen.envA[1] ),
    .ZN(_107_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _320_ (
    .I(\signal_gen.tonegenA.counter[4] ),
    .ZN(_108_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _321_ (
    .I(\signal_gen.tonegenA.counter[3] ),
    .ZN(_109_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _322_ (
    .I(\signal_gen.tonegenA.counter[2] ),
    .ZN(_110_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _323_ (
    .I(\signal_gen.tonegenA.counter[1] ),
    .ZN(_111_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _324_ (
    .I(rst_n),
    .ZN(_016_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _325_ (
    .I(address_in[1]),
    .ZN(_112_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _326_ (
    .I(address_in[0]),
    .ZN(_113_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _327_ (
    .I(\signal_gen.pwmGen.clk_cnt[7] ),
    .ZN(_114_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _328_ (
    .I(\signal_gen.mix.mixout[6] ),
    .ZN(_115_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _329_ (
    .I(\signal_gen.mix.mixout[5] ),
    .ZN(_116_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _330_ (
    .I(\signal_gen.pwmGen.clk_cnt[4] ),
    .ZN(_117_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _331_ (
    .I(\signal_gen.pwmGen.clk_cnt[3] ),
    .ZN(_118_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _332_ (
    .I(\signal_gen.pwmGen.clk_cnt[2] ),
    .ZN(_119_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _333_ (
    .I(\signal_gen.noise_gen.noise_reg[2] ),
    .ZN(_120_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand4_1 _334_ (
    .A1(_112_),
    .A2(address_in[0]),
    .A3(address_in[2]),
    .A4(write_strobe_in),
    .ZN(_121_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _335_ (
    .I0(data_in[0]),
    .I1(\signal_gen.enableN ),
    .S(_121_),
    .Z(_101_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _336_ (
    .A1(address_in[0]),
    .A2(address_in[2]),
    .ZN(_122_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _337_ (
    .A1(_112_),
    .A2(write_strobe_in),
    .A3(_122_),
    .ZN(_123_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _338_ (
    .I0(data_in[4]),
    .I1(\signal_gen.periodA[4] ),
    .S(_123_),
    .Z(_046_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _339_ (
    .I0(data_in[3]),
    .I1(\signal_gen.periodA[3] ),
    .S(_123_),
    .Z(_045_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _340_ (
    .I0(data_in[2]),
    .I1(\signal_gen.periodA[2] ),
    .S(_123_),
    .Z(_044_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _341_ (
    .A1(data_in[1]),
    .A2(_123_),
    .ZN(_124_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _342_ (
    .A1(_102_),
    .A2(_123_),
    .B(_124_),
    .ZN(_043_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _343_ (
    .I0(data_in[0]),
    .I1(\signal_gen.periodA[0] ),
    .S(_123_),
    .Z(_042_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand4_1 _344_ (
    .A1(_112_),
    .A2(_113_),
    .A3(address_in[2]),
    .A4(write_strobe_in),
    .ZN(_125_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _345_ (
    .I0(data_in[3]),
    .I1(\signal_gen.volN[3] ),
    .S(_125_),
    .Z(_041_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _346_ (
    .I0(data_in[2]),
    .I1(\signal_gen.volN[2] ),
    .S(_125_),
    .Z(_040_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _347_ (
    .I0(data_in[1]),
    .I1(\signal_gen.volN[1] ),
    .S(_125_),
    .Z(_039_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _348_ (
    .I0(data_in[0]),
    .I1(\signal_gen.volN[0] ),
    .S(_125_),
    .Z(_038_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _349_ (
    .A1(address_in[1]),
    .A2(write_strobe_in),
    .A3(_122_),
    .ZN(_126_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _350_ (
    .A1(data_in[3]),
    .A2(_126_),
    .ZN(_127_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _351_ (
    .A1(_103_),
    .A2(_126_),
    .B(_127_),
    .ZN(_037_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _352_ (
    .I0(data_in[2]),
    .I1(\signal_gen.volA[2] ),
    .S(_126_),
    .Z(_036_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _353_ (
    .I0(data_in[1]),
    .I1(\signal_gen.volA[1] ),
    .S(_126_),
    .Z(_035_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _354_ (
    .I0(data_in[0]),
    .I1(\signal_gen.volA[0] ),
    .S(_126_),
    .Z(_034_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _355_ (
    .A1(\clk_scaler.counter[2] ),
    .A2(\clk_scaler.counter[0] ),
    .A3(\clk_scaler.counter[1] ),
    .ZN(_128_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _356_ (
    .A1(\clk_scaler.counter[4] ),
    .A2(\clk_scaler.counter[3] ),
    .ZN(_129_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _357_ (
    .A1(\clk_scaler.counter[7] ),
    .A2(\clk_scaler.counter[6] ),
    .A3(\clk_scaler.counter[5] ),
    .ZN(_130_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _358_ (
    .A1(_128_),
    .A2(_129_),
    .B(_130_),
    .ZN(_131_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _359_ (
    .I(_131_),
    .ZN(_132_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _360_ (
    .A1(ena),
    .A2(_132_),
    .ZN(_133_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _361_ (
    .A1(\clk_scaler.counter[0] ),
    .A2(_133_),
    .ZN(_000_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xnor2_1 _362_ (
    .A1(\clk_scaler.counter[0] ),
    .A2(\clk_scaler.counter[1] ),
    .ZN(_134_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _363_ (
    .A1(_133_),
    .A2(_134_),
    .ZN(_001_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and3_1 _364_ (
    .A1(\clk_scaler.counter[2] ),
    .A2(\clk_scaler.counter[0] ),
    .A3(\clk_scaler.counter[1] ),
    .Z(_135_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _365_ (
    .A1(\clk_scaler.counter[0] ),
    .A2(\clk_scaler.counter[1] ),
    .B(\clk_scaler.counter[2] ),
    .ZN(_136_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _366_ (
    .A1(_133_),
    .A2(_135_),
    .A3(_136_),
    .ZN(_002_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _367_ (
    .A1(\clk_scaler.counter[3] ),
    .A2(_135_),
    .ZN(_137_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or2_1 _368_ (
    .A1(\clk_scaler.counter[3] ),
    .A2(_135_),
    .Z(_138_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and4_1 _369_ (
    .A1(ena),
    .A2(_132_),
    .A3(_137_),
    .A4(_138_),
    .Z(_003_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _370_ (
    .A1(\clk_scaler.counter[4] ),
    .A2(_137_),
    .Z(_139_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _371_ (
    .A1(_133_),
    .A2(_139_),
    .ZN(_004_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _372_ (
    .A1(_102_),
    .A2(\signal_gen.tonegenA.counter[1] ),
    .B(\signal_gen.tonegenA.counter[0] ),
    .ZN(_140_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi222_1 _373_ (
    .A1(\signal_gen.periodA[2] ),
    .A2(_110_),
    .B1(_111_),
    .B2(\signal_gen.periodA[1] ),
    .C1(_140_),
    .C2(\signal_gen.periodA[0] ),
    .ZN(_141_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai22_1 _374_ (
    .A1(\signal_gen.periodA[3] ),
    .A2(_109_),
    .B1(_110_),
    .B2(\signal_gen.periodA[2] ),
    .ZN(_142_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _375_ (
    .A1(\signal_gen.periodA[4] ),
    .A2(_108_),
    .B1(_109_),
    .B2(\signal_gen.periodA[3] ),
    .ZN(_143_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _376_ (
    .A1(_141_),
    .A2(_142_),
    .B(_143_),
    .ZN(_144_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _377_ (
    .A1(\signal_gen.periodA[4] ),
    .A2(_108_),
    .B(_144_),
    .ZN(_145_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai211_1 _378_ (
    .A1(\signal_gen.tonegenA.counter[5] ),
    .A2(_145_),
    .B(\signal_gen.tonegenA.counter[7] ),
    .C(\signal_gen.tonegenA.counter[6] ),
    .ZN(_146_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _379_ (
    .A1(\signal_gen.enableA ),
    .A2(_146_),
    .ZN(_147_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _380_ (
    .A1(\signal_gen.tonegenA.counter[0] ),
    .A2(_147_),
    .ZN(_008_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _381_ (
    .A1(_111_),
    .A2(\signal_gen.tonegenA.counter[0] ),
    .Z(_148_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _382_ (
    .A1(_147_),
    .A2(_148_),
    .ZN(_009_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and3_1 _383_ (
    .A1(\signal_gen.tonegenA.counter[2] ),
    .A2(\signal_gen.tonegenA.counter[1] ),
    .A3(\signal_gen.tonegenA.counter[0] ),
    .Z(_149_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _384_ (
    .A1(\signal_gen.tonegenA.counter[1] ),
    .A2(\signal_gen.tonegenA.counter[0] ),
    .B(\signal_gen.tonegenA.counter[2] ),
    .ZN(_150_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _385_ (
    .A1(_147_),
    .A2(_149_),
    .A3(_150_),
    .ZN(_010_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _386_ (
    .A1(\signal_gen.tonegenA.counter[3] ),
    .A2(_149_),
    .Z(_151_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _387_ (
    .A1(\signal_gen.tonegenA.counter[3] ),
    .A2(_149_),
    .ZN(_152_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _388_ (
    .A1(_147_),
    .A2(_151_),
    .A3(_152_),
    .ZN(_011_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _389_ (
    .A1(\signal_gen.tonegenA.counter[4] ),
    .A2(_151_),
    .Z(_153_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _390_ (
    .A1(\signal_gen.tonegenA.counter[4] ),
    .A2(_151_),
    .ZN(_154_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _391_ (
    .A1(_147_),
    .A2(_153_),
    .A3(_154_),
    .ZN(_012_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _392_ (
    .A1(\signal_gen.tonegenA.counter[5] ),
    .A2(_153_),
    .Z(_155_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _393_ (
    .A1(\signal_gen.tonegenA.counter[5] ),
    .A2(_153_),
    .ZN(_156_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _394_ (
    .A1(_147_),
    .A2(_155_),
    .A3(_156_),
    .ZN(_013_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _395_ (
    .A1(\signal_gen.tonegenA.counter[6] ),
    .A2(_155_),
    .ZN(_157_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or2_1 _396_ (
    .A1(\signal_gen.tonegenA.counter[6] ),
    .A2(_155_),
    .Z(_158_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and4_1 _397_ (
    .A1(\signal_gen.enableA ),
    .A2(_146_),
    .A3(_157_),
    .A4(_158_),
    .Z(_014_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _398_ (
    .A1(\signal_gen.tonegenA.counter[7] ),
    .A2(_157_),
    .Z(_159_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _399_ (
    .A1(_147_),
    .A2(_159_),
    .ZN(_015_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _400_ (
    .A1(\signal_gen.mix.started ),
    .A2(_016_),
    .ZN(_160_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _401_ (
    .A1(\signal_gen.mix.started ),
    .A2(rst_n),
    .Z(_161_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _402_ (
    .A1(\signal_gen.mix.started ),
    .A2(rst_n),
    .ZN(_162_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _403_ (
    .A1(\signal_gen.enableN ),
    .A2(\signal_gen.mix.noise ),
    .ZN(_163_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _404_ (
    .A1(_162_),
    .A2(_163_),
    .ZN(_164_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _405_ (
    .A1(\signal_gen.mix.n_val[1] ),
    .A2(_160_),
    .B1(_164_),
    .B2(\signal_gen.volN[0] ),
    .ZN(_165_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _406_ (
    .I(_165_),
    .ZN(_030_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _407_ (
    .A1(\signal_gen.mix.n_val[2] ),
    .A2(_160_),
    .B1(_164_),
    .B2(\signal_gen.volN[1] ),
    .ZN(_166_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _408_ (
    .I(_166_),
    .ZN(_031_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _409_ (
    .A1(\signal_gen.mix.n_val[3] ),
    .A2(_160_),
    .B1(_164_),
    .B2(\signal_gen.volN[2] ),
    .ZN(_167_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _410_ (
    .I(_167_),
    .ZN(_032_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _411_ (
    .A1(\signal_gen.mix.n_val[4] ),
    .A2(_160_),
    .B1(_164_),
    .B2(\signal_gen.volN[3] ),
    .ZN(_168_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _412_ (
    .I(_168_),
    .ZN(_033_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _413_ (
    .A1(clk_scaled),
    .A2(_131_),
    .Z(_169_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _414_ (
    .A1(ena),
    .A2(_169_),
    .Z(_047_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _415_ (
    .A1(rst_n),
    .A2(_121_),
    .ZN(_170_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _416_ (
    .I0(\signal_gen.enableA ),
    .I1(data_in[1]),
    .S(_170_),
    .Z(_048_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _417_ (
    .A1(\signal_gen.envA_gen.timer[1] ),
    .A2(\signal_gen.envA_gen.timer[3] ),
    .A3(\signal_gen.envA_gen.timer[2] ),
    .ZN(_171_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _418_ (
    .A1(\signal_gen.envA_gen.state[0] ),
    .A2(\signal_gen.envA_gen.state[1] ),
    .ZN(_172_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor4_1 _419_ (
    .A1(\signal_gen.envA_gen.timer[0] ),
    .A2(\signal_gen.envA_gen.timer[3] ),
    .A3(\signal_gen.envA_gen.timer[2] ),
    .A4(_172_),
    .ZN(_173_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or2_1 _420_ (
    .A1(_171_),
    .A2(_173_),
    .Z(_174_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _421_ (
    .A1(\signal_gen.envA_gen.state[0] ),
    .A2(_174_),
    .ZN(_175_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or2_1 _422_ (
    .A1(\signal_gen.envA_gen.state[0] ),
    .A2(_105_),
    .Z(_176_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _423_ (
    .A1(\signal_gen.envA_gen.state[0] ),
    .A2(\signal_gen.envA_gen.state[1] ),
    .ZN(_177_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _424_ (
    .A1(\signal_gen.enableA ),
    .A2(_176_),
    .ZN(_178_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _425_ (
    .A1(\signal_gen.enableA ),
    .A2(_177_),
    .B(_178_),
    .ZN(_179_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand4_1 _426_ (
    .A1(\signal_gen.envA[0] ),
    .A2(\signal_gen.envA_gen.state[0] ),
    .A3(\signal_gen.envA[2] ),
    .A4(\signal_gen.envA[1] ),
    .ZN(_180_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _427_ (
    .A1(\signal_gen.envA_gen.state[1] ),
    .A2(_106_),
    .A3(_180_),
    .ZN(_181_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _428_ (
    .A1(_175_),
    .A2(_179_),
    .A3(_181_),
    .ZN(_182_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or3_1 _429_ (
    .A1(\signal_gen.envA[0] ),
    .A2(\signal_gen.envA[2] ),
    .A3(\signal_gen.envA[1] ),
    .Z(_183_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _430_ (
    .A1(\signal_gen.envA[3] ),
    .A2(_172_),
    .A3(_183_),
    .ZN(_184_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _431_ (
    .A1(_175_),
    .A2(_179_),
    .A3(_184_),
    .ZN(_185_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _432_ (
    .A1(\signal_gen.envA_gen.state[1] ),
    .A2(_185_),
    .ZN(_186_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _433_ (
    .A1(_182_),
    .A2(_186_),
    .ZN(_049_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _434_ (
    .A1(_181_),
    .A2(_184_),
    .ZN(_187_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and3_1 _435_ (
    .A1(_179_),
    .A2(_182_),
    .A3(_185_),
    .Z(_050_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _436_ (
    .A1(_106_),
    .A2(_171_),
    .ZN(_188_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _437_ (
    .A1(_183_),
    .A2(_188_),
    .B(_176_),
    .ZN(_189_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _438_ (
    .A1(_175_),
    .A2(_187_),
    .ZN(_190_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _439_ (
    .A1(_189_),
    .A2(_190_),
    .ZN(_191_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _440_ (
    .I(_191_),
    .ZN(_192_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _441_ (
    .A1(\signal_gen.envA_gen.state[0] ),
    .A2(\signal_gen.envA_gen.state[1] ),
    .B(_191_),
    .ZN(_193_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _442_ (
    .A1(\signal_gen.envA[0] ),
    .A2(_192_),
    .ZN(_194_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _443_ (
    .A1(\signal_gen.envA[0] ),
    .A2(_193_),
    .B(_194_),
    .ZN(_051_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _444_ (
    .A1(_105_),
    .A2(_107_),
    .ZN(_195_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _445_ (
    .A1(\signal_gen.envA_gen.state[1] ),
    .A2(\signal_gen.envA[1] ),
    .Z(_196_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xnor2_1 _446_ (
    .A1(\signal_gen.envA[0] ),
    .A2(_196_),
    .ZN(_197_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai22_1 _447_ (
    .A1(_107_),
    .A2(_191_),
    .B1(_193_),
    .B2(_197_),
    .ZN(_052_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _448_ (
    .A1(\signal_gen.envA[2] ),
    .A2(_192_),
    .ZN(_198_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _449_ (
    .A1(\signal_gen.envA_gen.state[1] ),
    .A2(\signal_gen.envA[2] ),
    .ZN(_199_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _450_ (
    .A1(\signal_gen.envA_gen.state[1] ),
    .A2(\signal_gen.envA[2] ),
    .ZN(_200_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _451_ (
    .A1(\signal_gen.envA[0] ),
    .A2(_196_),
    .B(_195_),
    .ZN(_201_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor3_1 _452_ (
    .A1(\signal_gen.envA_gen.state[1] ),
    .A2(\signal_gen.envA[2] ),
    .A3(_201_),
    .Z(_202_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _453_ (
    .A1(_193_),
    .A2(_202_),
    .B(_198_),
    .ZN(_053_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _454_ (
    .A1(_200_),
    .A2(_201_),
    .B(_199_),
    .ZN(_203_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor3_1 _455_ (
    .A1(\signal_gen.envA_gen.state[1] ),
    .A2(_106_),
    .A3(_203_),
    .Z(_204_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai22_1 _456_ (
    .A1(_106_),
    .A2(_191_),
    .B1(_193_),
    .B2(_204_),
    .ZN(_054_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xnor2_1 _457_ (
    .A1(\signal_gen.mix.waveA ),
    .A2(_146_),
    .ZN(_205_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _458_ (
    .A1(\signal_gen.enableA ),
    .A2(_205_),
    .Z(_055_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _459_ (
    .A1(\signal_gen.mix.sum[0] ),
    .A2(_161_),
    .Z(_056_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _460_ (
    .A1(\signal_gen.mix.sum[1] ),
    .A2(_161_),
    .Z(_057_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _461_ (
    .A1(\signal_gen.mix.sum[2] ),
    .A2(_161_),
    .Z(_058_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _462_ (
    .A1(\signal_gen.mix.sum[3] ),
    .A2(_161_),
    .Z(_059_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _463_ (
    .A1(\signal_gen.mix.sum[4] ),
    .A2(_161_),
    .Z(_060_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _464_ (
    .A1(\signal_gen.mix.sum[5] ),
    .A2(_161_),
    .Z(_061_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _465_ (
    .A1(_174_),
    .A2(_177_),
    .ZN(_206_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _466_ (
    .A1(\signal_gen.envA_gen.state[0] ),
    .A2(\signal_gen.envA_gen.state[1] ),
    .B(\signal_gen.envA_gen.timer[0] ),
    .ZN(_207_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _467_ (
    .A1(\signal_gen.envA_gen.timer[0] ),
    .A2(_177_),
    .Z(_208_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _468_ (
    .A1(_206_),
    .A2(_208_),
    .ZN(_062_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _469_ (
    .A1(_104_),
    .A2(_207_),
    .B(_206_),
    .ZN(_063_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _470_ (
    .A1(\signal_gen.envA_gen.timer[2] ),
    .A2(_177_),
    .Z(_064_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _471_ (
    .A1(\signal_gen.envA_gen.timer[3] ),
    .A2(_177_),
    .Z(_065_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _472_ (
    .A1(\signal_gen.mix.a_val[0] ),
    .A2(_160_),
    .ZN(_209_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _473_ (
    .A1(\signal_gen.volA[1] ),
    .A2(\signal_gen.envA[1] ),
    .ZN(_210_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _474_ (
    .A1(\signal_gen.volA[0] ),
    .A2(\signal_gen.envA[0] ),
    .B(_210_),
    .ZN(_211_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _475_ (
    .A1(\signal_gen.volA[2] ),
    .A2(\signal_gen.envA[0] ),
    .B(_211_),
    .ZN(_212_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _476_ (
    .A1(\signal_gen.volA[0] ),
    .A2(\signal_gen.envA[2] ),
    .ZN(_213_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _477_ (
    .A1(_212_),
    .A2(_213_),
    .ZN(_214_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _478_ (
    .A1(\signal_gen.volA[1] ),
    .A2(\signal_gen.envA[3] ),
    .ZN(_215_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _479_ (
    .A1(\signal_gen.volA[0] ),
    .A2(\signal_gen.envA[3] ),
    .ZN(_216_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _480_ (
    .A1(\signal_gen.volA[1] ),
    .A2(\signal_gen.envA[2] ),
    .ZN(_217_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xnor2_1 _481_ (
    .A1(_216_),
    .A2(_217_),
    .ZN(_218_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _482_ (
    .A1(\signal_gen.volA[3] ),
    .A2(\signal_gen.envA[1] ),
    .ZN(_219_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and4_1 _483_ (
    .A1(\signal_gen.volA[3] ),
    .A2(\signal_gen.volA[2] ),
    .A3(\signal_gen.envA[0] ),
    .A4(\signal_gen.envA[1] ),
    .Z(_220_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _484_ (
    .A1(\signal_gen.volA[3] ),
    .A2(\signal_gen.envA[0] ),
    .B1(\signal_gen.envA[1] ),
    .B2(\signal_gen.volA[2] ),
    .ZN(_221_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _485_ (
    .A1(\signal_gen.volA[2] ),
    .A2(\signal_gen.volA[0] ),
    .B(\signal_gen.envA[0] ),
    .ZN(_222_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or4_1 _486_ (
    .A1(_210_),
    .A2(_220_),
    .A3(_221_),
    .A4(_222_),
    .Z(_223_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai22_1 _487_ (
    .A1(_220_),
    .A2(_221_),
    .B1(_222_),
    .B2(_210_),
    .ZN(_224_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _488_ (
    .A1(_223_),
    .A2(_224_),
    .ZN(_225_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _489_ (
    .A1(_218_),
    .A2(_225_),
    .Z(_226_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _490_ (
    .A1(_214_),
    .A2(_226_),
    .ZN(_227_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _491_ (
    .A1(_214_),
    .A2(_226_),
    .Z(_228_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _492_ (
    .A1(\signal_gen.enableA ),
    .A2(\signal_gen.mix.waveA ),
    .A3(_161_),
    .ZN(_229_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai31_1 _493_ (
    .A1(_227_),
    .A2(_228_),
    .A3(_229_),
    .B(_209_),
    .ZN(_066_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _494_ (
    .A1(\signal_gen.mix.a_val[1] ),
    .A2(_160_),
    .ZN(_230_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _495_ (
    .A1(\signal_gen.volA[2] ),
    .A2(\signal_gen.envA[3] ),
    .ZN(_231_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _496_ (
    .A1(\signal_gen.volA[2] ),
    .A2(\signal_gen.envA[2] ),
    .ZN(_232_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _497_ (
    .A1(_215_),
    .A2(_232_),
    .ZN(_233_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _498_ (
    .A1(_215_),
    .A2(_232_),
    .Z(_234_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _499_ (
    .A1(\signal_gen.volA[2] ),
    .A2(\signal_gen.envA[0] ),
    .B(_219_),
    .ZN(_235_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _500_ (
    .I0(_219_),
    .I1(_235_),
    .S(_223_),
    .Z(_236_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _501_ (
    .A1(_234_),
    .A2(_236_),
    .Z(_237_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai22_1 _502_ (
    .A1(_213_),
    .A2(_215_),
    .B1(_218_),
    .B2(_225_),
    .ZN(_238_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _503_ (
    .A1(_237_),
    .A2(_238_),
    .Z(_239_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _504_ (
    .A1(_237_),
    .A2(_238_),
    .Z(_240_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xnor2_1 _505_ (
    .A1(_228_),
    .A2(_240_),
    .ZN(_241_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _506_ (
    .A1(_229_),
    .A2(_241_),
    .B(_230_),
    .ZN(_067_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _507_ (
    .A1(\signal_gen.mix.a_val[2] ),
    .A2(_160_),
    .ZN(_242_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _508_ (
    .A1(_103_),
    .A2(_210_),
    .A3(_222_),
    .ZN(_243_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or2_1 _509_ (
    .A1(_220_),
    .A2(_243_),
    .Z(_244_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _510_ (
    .A1(\signal_gen.volA[3] ),
    .A2(\signal_gen.envA[2] ),
    .ZN(_245_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _511_ (
    .A1(\signal_gen.volA[3] ),
    .A2(\signal_gen.envA[3] ),
    .ZN(_246_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _512_ (
    .A1(_231_),
    .A2(_245_),
    .Z(_247_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _513_ (
    .A1(_244_),
    .A2(_247_),
    .ZN(_248_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xnor2_1 _514_ (
    .A1(_244_),
    .A2(_247_),
    .ZN(_249_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _515_ (
    .A1(_234_),
    .A2(_236_),
    .B(_233_),
    .ZN(_250_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _516_ (
    .A1(_249_),
    .A2(_250_),
    .ZN(_251_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _517_ (
    .A1(_249_),
    .A2(_250_),
    .Z(_252_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _518_ (
    .A1(_228_),
    .A2(_240_),
    .A3(_252_),
    .ZN(_253_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi211_1 _519_ (
    .A1(_228_),
    .A2(_240_),
    .B(_252_),
    .C(_239_),
    .ZN(_254_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _520_ (
    .A1(_239_),
    .A2(_252_),
    .B(_229_),
    .ZN(_255_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _521_ (
    .A1(_253_),
    .A2(_255_),
    .ZN(_256_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _522_ (
    .A1(_254_),
    .A2(_256_),
    .B(_242_),
    .ZN(_068_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _523_ (
    .A1(\signal_gen.mix.a_val[3] ),
    .A2(_160_),
    .ZN(_257_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _524_ (
    .A1(_239_),
    .A2(_252_),
    .B(_251_),
    .ZN(_258_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _525_ (
    .A1(_232_),
    .A2(_248_),
    .B(_246_),
    .ZN(_259_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _526_ (
    .A1(_246_),
    .A2(_248_),
    .Z(_260_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or2_1 _527_ (
    .A1(_259_),
    .A2(_260_),
    .Z(_261_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and3_1 _528_ (
    .A1(_253_),
    .A2(_258_),
    .A3(_261_),
    .Z(_262_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _529_ (
    .A1(_253_),
    .A2(_258_),
    .B(_261_),
    .ZN(_263_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai31_1 _530_ (
    .A1(_229_),
    .A2(_262_),
    .A3(_263_),
    .B(_257_),
    .ZN(_069_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _531_ (
    .A1(_259_),
    .A2(_263_),
    .ZN(_264_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _532_ (
    .A1(\signal_gen.mix.a_val[4] ),
    .A2(_160_),
    .ZN(_265_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _533_ (
    .A1(_229_),
    .A2(_264_),
    .B(_265_),
    .ZN(_070_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _534_ (
    .A1(\signal_gen.mix.sum[0] ),
    .A2(_160_),
    .B1(_161_),
    .B2(\signal_gen.mix.a_val[0] ),
    .ZN(_266_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _535_ (
    .I(_266_),
    .ZN(_071_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _536_ (
    .A1(\signal_gen.mix.a_val[1] ),
    .A2(\signal_gen.mix.n_val[1] ),
    .ZN(_267_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _537_ (
    .A1(\signal_gen.mix.a_val[1] ),
    .A2(\signal_gen.mix.n_val[1] ),
    .Z(_268_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _538_ (
    .A1(\signal_gen.mix.sum[1] ),
    .A2(_160_),
    .B1(_161_),
    .B2(_268_),
    .ZN(_269_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _539_ (
    .I(_269_),
    .ZN(_072_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _540_ (
    .A1(\signal_gen.mix.sum[2] ),
    .A2(_160_),
    .ZN(_270_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _541_ (
    .A1(\signal_gen.mix.a_val[2] ),
    .A2(\signal_gen.mix.n_val[2] ),
    .ZN(_271_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _542_ (
    .A1(\signal_gen.mix.a_val[2] ),
    .A2(\signal_gen.mix.n_val[2] ),
    .ZN(_272_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor3_1 _543_ (
    .A1(\signal_gen.mix.a_val[2] ),
    .A2(\signal_gen.mix.n_val[2] ),
    .A3(_267_),
    .Z(_273_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _544_ (
    .A1(_162_),
    .A2(_273_),
    .B(_270_),
    .ZN(_073_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _545_ (
    .A1(\signal_gen.mix.a_val[3] ),
    .A2(\signal_gen.mix.n_val[3] ),
    .ZN(_274_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _546_ (
    .I(_274_),
    .ZN(_275_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _547_ (
    .A1(\signal_gen.mix.a_val[3] ),
    .A2(\signal_gen.mix.n_val[3] ),
    .Z(_276_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _548_ (
    .A1(_267_),
    .A2(_272_),
    .B(_271_),
    .ZN(_277_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _549_ (
    .A1(_276_),
    .A2(_277_),
    .Z(_278_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _550_ (
    .A1(_276_),
    .A2(_277_),
    .Z(_279_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _551_ (
    .I0(\signal_gen.mix.sum[3] ),
    .I1(_279_),
    .S(\signal_gen.mix.started ),
    .Z(_280_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _552_ (
    .A1(rst_n),
    .A2(_280_),
    .ZN(_281_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _553_ (
    .I(_281_),
    .ZN(_074_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _554_ (
    .A1(\signal_gen.mix.sum[4] ),
    .A2(_160_),
    .ZN(_282_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _555_ (
    .A1(\signal_gen.mix.a_val[4] ),
    .A2(\signal_gen.mix.n_val[4] ),
    .Z(_283_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _556_ (
    .A1(\signal_gen.mix.a_val[4] ),
    .A2(\signal_gen.mix.n_val[4] ),
    .Z(_284_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _557_ (
    .A1(_275_),
    .A2(_278_),
    .A3(_284_),
    .ZN(_285_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _558_ (
    .A1(_275_),
    .A2(_278_),
    .B(_284_),
    .ZN(_286_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _559_ (
    .A1(_161_),
    .A2(_286_),
    .ZN(_287_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _560_ (
    .A1(_285_),
    .A2(_287_),
    .B(_282_),
    .ZN(_075_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _561_ (
    .A1(\signal_gen.mix.started ),
    .A2(_286_),
    .ZN(_288_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai221_1 _562_ (
    .A1(\signal_gen.mix.sum[5] ),
    .A2(\signal_gen.mix.started ),
    .B1(_283_),
    .B2(_288_),
    .C(rst_n),
    .ZN(_289_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _563_ (
    .I(_289_),
    .ZN(_076_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _564_ (
    .I0(\signal_gen.noise_gen.noise_reg[0] ),
    .I1(\signal_gen.noise_gen.feedback ),
    .S(\signal_gen.enableN ),
    .Z(_077_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _565_ (
    .I0(\signal_gen.mix.noise ),
    .I1(\signal_gen.noise_gen.noise_reg[0] ),
    .S(\signal_gen.enableN ),
    .Z(_078_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _566_ (
    .A1(\signal_gen.enableN ),
    .A2(_120_),
    .B(_163_),
    .ZN(_079_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _567_ (
    .A1(\signal_gen.enableN ),
    .A2(\signal_gen.noise_gen.noise_reg[3] ),
    .ZN(_290_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _568_ (
    .A1(\signal_gen.enableN ),
    .A2(_120_),
    .B(_290_),
    .ZN(_080_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _569_ (
    .I0(\signal_gen.noise_gen.noise_reg[4] ),
    .I1(\signal_gen.noise_gen.noise_reg[3] ),
    .S(\signal_gen.enableN ),
    .Z(_081_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _570_ (
    .I0(\signal_gen.noise_gen.noise_reg[5] ),
    .I1(\signal_gen.noise_gen.noise_reg[4] ),
    .S(\signal_gen.enableN ),
    .Z(_082_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _571_ (
    .I0(\signal_gen.noise_gen.noise_reg[6] ),
    .I1(\signal_gen.noise_gen.noise_reg[5] ),
    .S(\signal_gen.enableN ),
    .Z(_083_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _572_ (
    .I0(\signal_gen.noise_gen.noise_reg[7] ),
    .I1(\signal_gen.noise_gen.noise_reg[6] ),
    .S(\signal_gen.enableN ),
    .Z(_084_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _573_ (
    .I0(\signal_gen.noise_gen.noise_reg[8] ),
    .I1(\signal_gen.noise_gen.noise_reg[7] ),
    .S(\signal_gen.enableN ),
    .Z(_085_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _574_ (
    .I0(\signal_gen.noise_gen.noise_reg[9] ),
    .I1(\signal_gen.noise_gen.noise_reg[8] ),
    .S(\signal_gen.enableN ),
    .Z(_086_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _575_ (
    .I0(\signal_gen.noise_gen.noise_reg[10] ),
    .I1(\signal_gen.noise_gen.noise_reg[9] ),
    .S(\signal_gen.enableN ),
    .Z(_087_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _576_ (
    .I0(\signal_gen.noise_gen.noise_reg[11] ),
    .I1(\signal_gen.noise_gen.noise_reg[10] ),
    .S(\signal_gen.enableN ),
    .Z(_088_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _577_ (
    .I0(\signal_gen.noise_gen.noise_reg[12] ),
    .I1(\signal_gen.noise_gen.noise_reg[11] ),
    .S(\signal_gen.enableN ),
    .Z(_089_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _578_ (
    .I0(\signal_gen.noise_gen.noise_reg[13] ),
    .I1(\signal_gen.noise_gen.noise_reg[12] ),
    .S(\signal_gen.enableN ),
    .Z(_090_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _579_ (
    .A1(\signal_gen.enableN ),
    .A2(rst_n),
    .ZN(_291_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _580_ (
    .A1(\signal_gen.noise_gen.noise_reg[4] ),
    .A2(\signal_gen.noise_gen.noise_reg[13] ),
    .Z(_292_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _581_ (
    .A1(\signal_gen.noise_gen.feedback ),
    .A2(_291_),
    .ZN(_293_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _582_ (
    .A1(_291_),
    .A2(_292_),
    .B(_293_),
    .ZN(_091_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _583_ (
    .A1(\signal_gen.mix.mixout[3] ),
    .A2(_118_),
    .B1(\signal_gen.mix.mixout[2] ),
    .B2(_119_),
    .ZN(_294_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai22_1 _584_ (
    .A1(\signal_gen.mix.mixout[4] ),
    .A2(_117_),
    .B1(\signal_gen.mix.mixout[3] ),
    .B2(_118_),
    .ZN(_295_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _585_ (
    .A1(\signal_gen.mix.mixout[4] ),
    .A2(_117_),
    .ZN(_296_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai221_1 _586_ (
    .A1(_116_),
    .A2(\signal_gen.pwmGen.clk_cnt[5] ),
    .B1(_294_),
    .B2(_295_),
    .C(_296_),
    .ZN(_297_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _587_ (
    .A1(_115_),
    .A2(\signal_gen.pwmGen.clk_cnt[6] ),
    .B1(_116_),
    .B2(\signal_gen.pwmGen.clk_cnt[5] ),
    .ZN(_298_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _588_ (
    .A1(_115_),
    .A2(\signal_gen.pwmGen.clk_cnt[6] ),
    .ZN(_299_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi221_1 _589_ (
    .A1(\signal_gen.mix.mixout[7] ),
    .A2(_114_),
    .B1(_297_),
    .B2(_298_),
    .C(_299_),
    .ZN(_300_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _590_ (
    .A1(\signal_gen.mix.mixout[7] ),
    .A2(_114_),
    .B(rst_n),
    .ZN(_301_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _591_ (
    .A1(_300_),
    .A2(_301_),
    .ZN(_092_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _592_ (
    .A1(_016_),
    .A2(\signal_gen.pwmGen.clk_cnt[0] ),
    .ZN(_093_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _593_ (
    .A1(\signal_gen.pwmGen.clk_cnt[0] ),
    .A2(\signal_gen.pwmGen.clk_cnt[1] ),
    .B(rst_n),
    .ZN(_302_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _594_ (
    .A1(\signal_gen.pwmGen.clk_cnt[0] ),
    .A2(\signal_gen.pwmGen.clk_cnt[1] ),
    .B(_302_),
    .ZN(_094_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _595_ (
    .A1(\signal_gen.pwmGen.clk_cnt[0] ),
    .A2(\signal_gen.pwmGen.clk_cnt[1] ),
    .B(\signal_gen.pwmGen.clk_cnt[2] ),
    .ZN(_303_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and3_1 _596_ (
    .A1(\signal_gen.pwmGen.clk_cnt[0] ),
    .A2(\signal_gen.pwmGen.clk_cnt[2] ),
    .A3(\signal_gen.pwmGen.clk_cnt[1] ),
    .Z(_304_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _597_ (
    .A1(_016_),
    .A2(_303_),
    .A3(_304_),
    .ZN(_095_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _598_ (
    .A1(\signal_gen.pwmGen.clk_cnt[3] ),
    .A2(_304_),
    .Z(_305_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _599_ (
    .A1(\signal_gen.pwmGen.clk_cnt[3] ),
    .A2(_304_),
    .B(rst_n),
    .ZN(_306_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _600_ (
    .A1(_305_),
    .A2(_306_),
    .ZN(_096_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _601_ (
    .A1(\signal_gen.pwmGen.clk_cnt[4] ),
    .A2(_305_),
    .Z(_307_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _602_ (
    .A1(\signal_gen.pwmGen.clk_cnt[4] ),
    .A2(_305_),
    .B(rst_n),
    .ZN(_308_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _603_ (
    .A1(_307_),
    .A2(_308_),
    .ZN(_097_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _604_ (
    .A1(\signal_gen.pwmGen.clk_cnt[5] ),
    .A2(_307_),
    .Z(_309_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _605_ (
    .A1(\signal_gen.pwmGen.clk_cnt[5] ),
    .A2(_307_),
    .B(rst_n),
    .ZN(_310_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _606_ (
    .A1(_309_),
    .A2(_310_),
    .ZN(_098_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _607_ (
    .A1(\signal_gen.pwmGen.clk_cnt[6] ),
    .A2(_309_),
    .ZN(_311_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _608_ (
    .A1(\signal_gen.pwmGen.clk_cnt[6] ),
    .A2(_309_),
    .B(rst_n),
    .ZN(_312_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _609_ (
    .A1(\signal_gen.pwmGen.clk_cnt[6] ),
    .A2(_309_),
    .B(_312_),
    .ZN(_099_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _610_ (
    .A1(\signal_gen.pwmGen.clk_cnt[7] ),
    .A2(_311_),
    .Z(_313_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _611_ (
    .A1(_016_),
    .A2(_313_),
    .ZN(_100_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _612_ (
    .I(rst_n),
    .ZN(_017_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _613_ (
    .I(rst_n),
    .ZN(_018_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _614_ (
    .I(rst_n),
    .ZN(_019_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _615_ (
    .I(rst_n),
    .ZN(_020_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _616_ (
    .I(rst_n),
    .ZN(_021_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _617_ (
    .I(rst_n),
    .ZN(_022_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _618_ (
    .I(rst_n),
    .ZN(_023_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _619_ (
    .I(rst_n),
    .ZN(_024_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _620_ (
    .I(rst_n),
    .ZN(_025_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _621_ (
    .I(rst_n),
    .ZN(_026_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _622_ (
    .I(rst_n),
    .ZN(_027_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _623_ (
    .I(rst_n),
    .ZN(_028_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _624_ (
    .I(rst_n),
    .ZN(_029_)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _625_ (
    .CLK(clk_scaled),
    .D(_030_),
    .Q(\signal_gen.mix.n_val[1] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _626_ (
    .CLK(clk_scaled),
    .D(_031_),
    .Q(\signal_gen.mix.n_val[2] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _627_ (
    .CLK(clk_scaled),
    .D(_032_),
    .Q(\signal_gen.mix.n_val[3] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _628_ (
    .CLK(clk_scaled),
    .D(_033_),
    .Q(\signal_gen.mix.n_val[4] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _629_ (
    .CLK(clk_scaled),
    .D(_034_),
    .Q(\signal_gen.volA[0] ),
    .RN(_016_)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _630_ (
    .CLK(clk_scaled),
    .D(_035_),
    .Q(\signal_gen.volA[1] ),
    .RN(_017_)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _631_ (
    .CLK(clk_scaled),
    .D(_036_),
    .Q(\signal_gen.volA[2] ),
    .RN(_018_)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffsnq_1 _632_ (
    .CLK(clk_scaled),
    .D(_037_),
    .Q(\signal_gen.volA[3] ),
    .SETN(_019_)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffsnq_1 _633_ (
    .CLK(clk_scaled),
    .D(_038_),
    .Q(\signal_gen.volN[0] ),
    .SETN(_020_)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffsnq_1 _634_ (
    .CLK(clk_scaled),
    .D(_039_),
    .Q(\signal_gen.volN[1] ),
    .SETN(_021_)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _635_ (
    .CLK(clk_scaled),
    .D(_040_),
    .Q(\signal_gen.volN[2] ),
    .RN(_022_)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _636_ (
    .CLK(clk_scaled),
    .D(_041_),
    .Q(\signal_gen.volN[3] ),
    .RN(_023_)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _637_ (
    .CLK(clk_scaled),
    .D(_042_),
    .Q(\signal_gen.periodA[0] ),
    .RN(_024_)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _638_ (
    .CLK(clk_scaled),
    .D(_043_),
    .Q(\signal_gen.periodA[1] ),
    .RN(_025_)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _639_ (
    .CLK(clk_scaled),
    .D(_044_),
    .Q(\signal_gen.periodA[2] ),
    .RN(_026_)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffsnq_1 _640_ (
    .CLK(clk_scaled),
    .D(_045_),
    .Q(\signal_gen.periodA[3] ),
    .SETN(_027_)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _641_ (
    .CLK(clk_scaled),
    .D(_046_),
    .Q(\signal_gen.periodA[4] ),
    .RN(_028_)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _642_ (
    .CLK(clk),
    .D(_047_),
    .Q(clk_scaled),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _643_ (
    .CLK(clk_scaled),
    .D(_048_),
    .Q(\signal_gen.enableA )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _644_ (
    .CLK(clk_scaled),
    .D(_049_),
    .Q(\signal_gen.envA_gen.state[1] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _645_ (
    .CLK(clk_scaled),
    .D(_050_),
    .Q(\signal_gen.envA_gen.state[0] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _646_ (
    .CLK(clk),
    .D(_000_),
    .Q(\clk_scaler.counter[0] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _647_ (
    .CLK(clk),
    .D(_001_),
    .Q(\clk_scaler.counter[1] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _648_ (
    .CLK(clk),
    .D(_002_),
    .Q(\clk_scaler.counter[2] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _649_ (
    .CLK(clk),
    .D(_003_),
    .Q(\clk_scaler.counter[3] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _650_ (
    .CLK(clk),
    .D(_004_),
    .Q(\clk_scaler.counter[4] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _651_ (
    .CLK(clk),
    .D(_005_),
    .Q(\clk_scaler.counter[5] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _652_ (
    .CLK(clk),
    .D(_006_),
    .Q(\clk_scaler.counter[6] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _653_ (
    .CLK(clk),
    .D(_007_),
    .Q(\clk_scaler.counter[7] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _654_ (
    .CLK(clk_scaled),
    .D(_051_),
    .Q(\signal_gen.envA[0] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _655_ (
    .CLK(clk_scaled),
    .D(_052_),
    .Q(\signal_gen.envA[1] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _656_ (
    .CLK(clk_scaled),
    .D(_053_),
    .Q(\signal_gen.envA[2] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _657_ (
    .CLK(clk_scaled),
    .D(_054_),
    .Q(\signal_gen.envA[3] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _658_ (
    .CLK(clk_scaled),
    .D(_055_),
    .Q(\signal_gen.mix.waveA ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _659_ (
    .CLK(clk_scaled),
    .D(_056_),
    .Q(\signal_gen.mix.mixout[2] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _660_ (
    .CLK(clk_scaled),
    .D(_057_),
    .Q(\signal_gen.mix.mixout[3] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _661_ (
    .CLK(clk_scaled),
    .D(_058_),
    .Q(\signal_gen.mix.mixout[4] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _662_ (
    .CLK(clk_scaled),
    .D(_059_),
    .Q(\signal_gen.mix.mixout[5] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _663_ (
    .CLK(clk_scaled),
    .D(_060_),
    .Q(\signal_gen.mix.mixout[6] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _664_ (
    .CLK(clk_scaled),
    .D(_061_),
    .Q(\signal_gen.mix.mixout[7] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _665_ (
    .CLK(clk_scaled),
    .D(_062_),
    .Q(\signal_gen.envA_gen.timer[0] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _666_ (
    .CLK(clk_scaled),
    .D(_063_),
    .Q(\signal_gen.envA_gen.timer[1] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _667_ (
    .CLK(clk_scaled),
    .D(_064_),
    .Q(\signal_gen.envA_gen.timer[2] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _668_ (
    .CLK(clk_scaled),
    .D(_065_),
    .Q(\signal_gen.envA_gen.timer[3] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _669_ (
    .CLK(clk_scaled),
    .D(_066_),
    .Q(\signal_gen.mix.a_val[0] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _670_ (
    .CLK(clk_scaled),
    .D(_067_),
    .Q(\signal_gen.mix.a_val[1] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _671_ (
    .CLK(clk_scaled),
    .D(_068_),
    .Q(\signal_gen.mix.a_val[2] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _672_ (
    .CLK(clk_scaled),
    .D(_069_),
    .Q(\signal_gen.mix.a_val[3] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _673_ (
    .CLK(clk_scaled),
    .D(_070_),
    .Q(\signal_gen.mix.a_val[4] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _674_ (
    .CLK(clk_scaled),
    .D(_071_),
    .Q(\signal_gen.mix.sum[0] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _675_ (
    .CLK(clk_scaled),
    .D(_072_),
    .Q(\signal_gen.mix.sum[1] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _676_ (
    .CLK(clk_scaled),
    .D(_073_),
    .Q(\signal_gen.mix.sum[2] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _677_ (
    .CLK(clk_scaled),
    .D(_074_),
    .Q(\signal_gen.mix.sum[3] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _678_ (
    .CLK(clk_scaled),
    .D(_075_),
    .Q(\signal_gen.mix.sum[4] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _679_ (
    .CLK(clk_scaled),
    .D(_076_),
    .Q(\signal_gen.mix.sum[5] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _680_ (
    .CLK(clk_scaled),
    .D(rst_n),
    .Q(\signal_gen.mix.started )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffsnq_1 _681_ (
    .CLK(clk_scaled),
    .D(_077_),
    .Q(\signal_gen.noise_gen.noise_reg[0] ),
    .SETN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _682_ (
    .CLK(clk_scaled),
    .D(_078_),
    .Q(\signal_gen.mix.noise ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _683_ (
    .CLK(clk_scaled),
    .D(_079_),
    .Q(\signal_gen.noise_gen.noise_reg[2] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _684_ (
    .CLK(clk_scaled),
    .D(_080_),
    .Q(\signal_gen.noise_gen.noise_reg[3] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _685_ (
    .CLK(clk_scaled),
    .D(_081_),
    .Q(\signal_gen.noise_gen.noise_reg[4] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffsnq_1 _686_ (
    .CLK(clk_scaled),
    .D(_082_),
    .Q(\signal_gen.noise_gen.noise_reg[5] ),
    .SETN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffsnq_1 _687_ (
    .CLK(clk_scaled),
    .D(_083_),
    .Q(\signal_gen.noise_gen.noise_reg[6] ),
    .SETN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffsnq_1 _688_ (
    .CLK(clk_scaled),
    .D(_084_),
    .Q(\signal_gen.noise_gen.noise_reg[7] ),
    .SETN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _689_ (
    .CLK(clk_scaled),
    .D(_085_),
    .Q(\signal_gen.noise_gen.noise_reg[8] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _690_ (
    .CLK(clk_scaled),
    .D(_086_),
    .Q(\signal_gen.noise_gen.noise_reg[9] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffsnq_1 _691_ (
    .CLK(clk_scaled),
    .D(_087_),
    .Q(\signal_gen.noise_gen.noise_reg[10] ),
    .SETN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffsnq_1 _692_ (
    .CLK(clk_scaled),
    .D(_088_),
    .Q(\signal_gen.noise_gen.noise_reg[11] ),
    .SETN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _693_ (
    .CLK(clk_scaled),
    .D(_089_),
    .Q(\signal_gen.noise_gen.noise_reg[12] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffsnq_1 _694_ (
    .CLK(clk_scaled),
    .D(_090_),
    .Q(\signal_gen.noise_gen.noise_reg[13] ),
    .SETN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _695_ (
    .CLK(clk_scaled),
    .D(_091_),
    .Q(\signal_gen.noise_gen.feedback )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _696_ (
    .CLK(clk_scaled),
    .D(_092_),
    .Q(signal_bit_out)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _697_ (
    .CLK(clk_scaled),
    .D(_008_),
    .Q(\signal_gen.tonegenA.counter[0] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _698_ (
    .CLK(clk_scaled),
    .D(_009_),
    .Q(\signal_gen.tonegenA.counter[1] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _699_ (
    .CLK(clk_scaled),
    .D(_010_),
    .Q(\signal_gen.tonegenA.counter[2] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _700_ (
    .CLK(clk_scaled),
    .D(_011_),
    .Q(\signal_gen.tonegenA.counter[3] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _701_ (
    .CLK(clk_scaled),
    .D(_012_),
    .Q(\signal_gen.tonegenA.counter[4] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _702_ (
    .CLK(clk_scaled),
    .D(_013_),
    .Q(\signal_gen.tonegenA.counter[5] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _703_ (
    .CLK(clk_scaled),
    .D(_014_),
    .Q(\signal_gen.tonegenA.counter[6] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _704_ (
    .CLK(clk_scaled),
    .D(_015_),
    .Q(\signal_gen.tonegenA.counter[7] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _705_ (
    .CLK(clk_scaled),
    .D(_093_),
    .Q(\signal_gen.pwmGen.clk_cnt[0] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _706_ (
    .CLK(clk_scaled),
    .D(_094_),
    .Q(\signal_gen.pwmGen.clk_cnt[1] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _707_ (
    .CLK(clk_scaled),
    .D(_095_),
    .Q(\signal_gen.pwmGen.clk_cnt[2] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _708_ (
    .CLK(clk_scaled),
    .D(_096_),
    .Q(\signal_gen.pwmGen.clk_cnt[3] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _709_ (
    .CLK(clk_scaled),
    .D(_097_),
    .Q(\signal_gen.pwmGen.clk_cnt[4] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _710_ (
    .CLK(clk_scaled),
    .D(_098_),
    .Q(\signal_gen.pwmGen.clk_cnt[5] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _711_ (
    .CLK(clk_scaled),
    .D(_099_),
    .Q(\signal_gen.pwmGen.clk_cnt[6] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _712_ (
    .CLK(clk_scaled),
    .D(_100_),
    .Q(\signal_gen.pwmGen.clk_cnt[7] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffsnq_1 _713_ (
    .CLK(clk_scaled),
    .D(_101_),
    .Q(\signal_gen.enableN ),
    .SETN(_029_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _714_ (
    .ZN(_007_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _715_ (
    .ZN(_006_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _716_ (
    .ZN(_005_)
  );
endmodule
