// Auto-generated by LibreLane
module tiny_tonegen(
`ifdef USE_POWER_PINS
  inout VDD,
  inout VSS,
`endif
  input clk,
  input rst_n,
  input ena,
  input[2:0] address_in,
  input write_strobe_in,
  input[4:0] data_in,
  output signal_bit_out
);
endmodule
