/* Generated by Yosys 0.57 (git sha1 3aca86049, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

module tiny_tonegen(clk, rst_n, ena, address_in, write_strobe_in, data_in, signal_bit_out);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input ena;
  wire ena;
  input [2:0] address_in;
  wire [2:0] address_in;
  input write_strobe_in;
  wire write_strobe_in;
  input [4:0] data_in;
  wire [4:0] data_in;
  output signal_bit_out;
  wire signal_bit_out;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire clk_scaled;
  wire \clk_scaler.counter[0] ;
  wire \clk_scaler.counter[1] ;
  wire \clk_scaler.counter[2] ;
  wire \clk_scaler.counter[3] ;
  wire \clk_scaler.counter[4] ;
  wire \clk_scaler.counter[5] ;
  wire \clk_scaler.counter[6] ;
  wire \clk_scaler.counter[7] ;
  wire \signal_gen.enableN ;
  wire \signal_gen.mix.mixout[3] ;
  wire \signal_gen.mix.mixout[4] ;
  wire \signal_gen.mix.mixout[5] ;
  wire \signal_gen.mix.mixout[6] ;
  wire \signal_gen.mix.n_val[1] ;
  wire \signal_gen.mix.n_val[2] ;
  wire \signal_gen.mix.n_val[3] ;
  wire \signal_gen.mix.n_val[4] ;
  wire \signal_gen.mix.noise ;
  wire \signal_gen.mix.started ;
  wire \signal_gen.mix.sum[1] ;
  wire \signal_gen.mix.sum[2] ;
  wire \signal_gen.mix.sum[3] ;
  wire \signal_gen.mix.sum[4] ;
  wire \signal_gen.noise_gen.feedback ;
  wire \signal_gen.noise_gen.noise_reg[0] ;
  wire \signal_gen.noise_gen.noise_reg[10] ;
  wire \signal_gen.noise_gen.noise_reg[11] ;
  wire \signal_gen.noise_gen.noise_reg[12] ;
  wire \signal_gen.noise_gen.noise_reg[13] ;
  wire \signal_gen.noise_gen.noise_reg[2] ;
  wire \signal_gen.noise_gen.noise_reg[3] ;
  wire \signal_gen.noise_gen.noise_reg[4] ;
  wire \signal_gen.noise_gen.noise_reg[5] ;
  wire \signal_gen.noise_gen.noise_reg[6] ;
  wire \signal_gen.noise_gen.noise_reg[7] ;
  wire \signal_gen.noise_gen.noise_reg[8] ;
  wire \signal_gen.noise_gen.noise_reg[9] ;
  wire \signal_gen.pwmGen.clk_cnt[0] ;
  wire \signal_gen.pwmGen.clk_cnt[1] ;
  wire \signal_gen.pwmGen.clk_cnt[2] ;
  wire \signal_gen.pwmGen.clk_cnt[3] ;
  wire \signal_gen.pwmGen.clk_cnt[4] ;
  wire \signal_gen.pwmGen.clk_cnt[5] ;
  wire \signal_gen.pwmGen.clk_cnt[6] ;
  wire \signal_gen.pwmGen.clk_cnt[7] ;
  wire \signal_gen.volN[0] ;
  wire \signal_gen.volN[1] ;
  wire \signal_gen.volN[2] ;
  wire \signal_gen.volN[3] ;
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _111_ (
    .I(\signal_gen.mix.n_val[4] ),
    .ZN(_055_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _112_ (
    .I(\signal_gen.mix.started ),
    .ZN(_056_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _113_ (
    .I(\signal_gen.mix.n_val[3] ),
    .ZN(_057_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _114_ (
    .I(\signal_gen.mix.n_val[2] ),
    .ZN(_058_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _115_ (
    .I(\signal_gen.mix.n_val[1] ),
    .ZN(_059_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _116_ (
    .I(rst_n),
    .ZN(_008_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _117_ (
    .I(address_in[1]),
    .ZN(_060_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _118_ (
    .I(address_in[0]),
    .ZN(_061_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _119_ (
    .I(\signal_gen.pwmGen.clk_cnt[6] ),
    .ZN(_062_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _120_ (
    .I(\signal_gen.mix.mixout[5] ),
    .ZN(_063_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _121_ (
    .I(\signal_gen.mix.mixout[4] ),
    .ZN(_064_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _122_ (
    .I(\signal_gen.mix.mixout[3] ),
    .ZN(_065_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand4_1 _123_ (
    .A1(address_in[2]),
    .A2(_060_),
    .A3(_061_),
    .A4(write_strobe_in),
    .ZN(_066_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _124_ (
    .I0(data_in[3]),
    .I1(\signal_gen.volN[3] ),
    .S(_066_),
    .Z(_040_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _125_ (
    .I0(data_in[2]),
    .I1(\signal_gen.volN[2] ),
    .S(_066_),
    .Z(_039_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _126_ (
    .I0(data_in[1]),
    .I1(\signal_gen.volN[1] ),
    .S(_066_),
    .Z(_038_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _127_ (
    .I0(data_in[0]),
    .I1(\signal_gen.volN[0] ),
    .S(_066_),
    .Z(_037_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand4_1 _128_ (
    .A1(address_in[2]),
    .A2(_060_),
    .A3(address_in[0]),
    .A4(write_strobe_in),
    .ZN(_067_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _129_ (
    .I0(data_in[0]),
    .I1(\signal_gen.enableN ),
    .S(_067_),
    .Z(_015_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _130_ (
    .A1(\clk_scaler.counter[0] ),
    .A2(\clk_scaler.counter[1] ),
    .A3(\clk_scaler.counter[2] ),
    .ZN(_068_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _131_ (
    .A1(\clk_scaler.counter[3] ),
    .A2(\clk_scaler.counter[4] ),
    .ZN(_069_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _132_ (
    .A1(\clk_scaler.counter[6] ),
    .A2(\clk_scaler.counter[7] ),
    .A3(\clk_scaler.counter[5] ),
    .ZN(_070_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _133_ (
    .A1(_068_),
    .A2(_069_),
    .B(_070_),
    .ZN(_071_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai211_1 _134_ (
    .A1(_068_),
    .A2(_069_),
    .B(_070_),
    .C(ena),
    .ZN(_072_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _135_ (
    .A1(\clk_scaler.counter[0] ),
    .A2(_072_),
    .ZN(_000_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xnor2_1 _136_ (
    .A1(\clk_scaler.counter[0] ),
    .A2(\clk_scaler.counter[1] ),
    .ZN(_073_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _137_ (
    .A1(_072_),
    .A2(_073_),
    .ZN(_001_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and3_1 _138_ (
    .A1(\clk_scaler.counter[0] ),
    .A2(\clk_scaler.counter[1] ),
    .A3(\clk_scaler.counter[2] ),
    .Z(_074_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _139_ (
    .A1(\clk_scaler.counter[0] ),
    .A2(\clk_scaler.counter[1] ),
    .B(\clk_scaler.counter[2] ),
    .ZN(_075_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _140_ (
    .A1(_072_),
    .A2(_074_),
    .A3(_075_),
    .ZN(_002_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _141_ (
    .A1(\clk_scaler.counter[3] ),
    .A2(_074_),
    .ZN(_076_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xnor2_1 _142_ (
    .A1(\clk_scaler.counter[3] ),
    .A2(_074_),
    .ZN(_077_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _143_ (
    .A1(_072_),
    .A2(_077_),
    .ZN(_003_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _144_ (
    .A1(\clk_scaler.counter[4] ),
    .A2(_076_),
    .Z(_078_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _145_ (
    .A1(_072_),
    .A2(_078_),
    .ZN(_004_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _146_ (
    .A1(_056_),
    .A2(_008_),
    .ZN(_079_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _147_ (
    .A1(\signal_gen.mix.sum[1] ),
    .A2(_079_),
    .Z(_041_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _148_ (
    .A1(\signal_gen.mix.sum[2] ),
    .A2(_079_),
    .Z(_042_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _149_ (
    .A1(\signal_gen.mix.sum[3] ),
    .A2(_079_),
    .Z(_043_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _150_ (
    .A1(\signal_gen.mix.sum[4] ),
    .A2(_079_),
    .Z(_044_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _151_ (
    .A1(_008_),
    .A2(\signal_gen.pwmGen.clk_cnt[0] ),
    .ZN(_045_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _152_ (
    .A1(\signal_gen.pwmGen.clk_cnt[1] ),
    .A2(\signal_gen.pwmGen.clk_cnt[0] ),
    .B(rst_n),
    .ZN(_080_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _153_ (
    .A1(\signal_gen.pwmGen.clk_cnt[1] ),
    .A2(\signal_gen.pwmGen.clk_cnt[0] ),
    .B(_080_),
    .ZN(_046_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _154_ (
    .A1(\signal_gen.pwmGen.clk_cnt[1] ),
    .A2(\signal_gen.pwmGen.clk_cnt[0] ),
    .B(\signal_gen.pwmGen.clk_cnt[2] ),
    .ZN(_081_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _155_ (
    .A1(\signal_gen.pwmGen.clk_cnt[1] ),
    .A2(\signal_gen.pwmGen.clk_cnt[0] ),
    .A3(\signal_gen.pwmGen.clk_cnt[2] ),
    .ZN(_082_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _156_ (
    .A1(rst_n),
    .A2(_082_),
    .ZN(_083_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _157_ (
    .A1(_081_),
    .A2(_083_),
    .ZN(_047_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and4_1 _158_ (
    .A1(\signal_gen.pwmGen.clk_cnt[3] ),
    .A2(\signal_gen.pwmGen.clk_cnt[1] ),
    .A3(\signal_gen.pwmGen.clk_cnt[0] ),
    .A4(\signal_gen.pwmGen.clk_cnt[2] ),
    .Z(_084_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _159_ (
    .A1(\signal_gen.pwmGen.clk_cnt[3] ),
    .A2(_082_),
    .Z(_085_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _160_ (
    .A1(_008_),
    .A2(_085_),
    .ZN(_048_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _161_ (
    .A1(\signal_gen.pwmGen.clk_cnt[4] ),
    .A2(_084_),
    .B(rst_n),
    .ZN(_086_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _162_ (
    .A1(\signal_gen.pwmGen.clk_cnt[4] ),
    .A2(_084_),
    .B(_086_),
    .ZN(_049_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _163_ (
    .A1(\signal_gen.pwmGen.clk_cnt[4] ),
    .A2(_084_),
    .B(\signal_gen.pwmGen.clk_cnt[5] ),
    .ZN(_087_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _164_ (
    .A1(\signal_gen.pwmGen.clk_cnt[5] ),
    .A2(\signal_gen.pwmGen.clk_cnt[4] ),
    .A3(_084_),
    .ZN(_088_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _165_ (
    .A1(rst_n),
    .A2(_088_),
    .ZN(_089_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _166_ (
    .A1(_087_),
    .A2(_089_),
    .ZN(_050_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand4_1 _167_ (
    .A1(\signal_gen.pwmGen.clk_cnt[6] ),
    .A2(\signal_gen.pwmGen.clk_cnt[5] ),
    .A3(\signal_gen.pwmGen.clk_cnt[4] ),
    .A4(_084_),
    .ZN(_090_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _168_ (
    .A1(rst_n),
    .A2(_090_),
    .ZN(_091_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _169_ (
    .A1(_062_),
    .A2(_088_),
    .B(_091_),
    .ZN(_051_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _170_ (
    .A1(\signal_gen.pwmGen.clk_cnt[7] ),
    .A2(_090_),
    .Z(_092_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _171_ (
    .A1(_008_),
    .A2(_092_),
    .ZN(_052_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and3_1 _172_ (
    .A1(\signal_gen.mix.started ),
    .A2(\signal_gen.enableN ),
    .A3(\signal_gen.mix.noise ),
    .Z(_093_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _173_ (
    .A1(_056_),
    .A2(\signal_gen.mix.n_val[1] ),
    .B1(_093_),
    .B2(\signal_gen.volN[0] ),
    .ZN(_094_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _174_ (
    .A1(_008_),
    .A2(_094_),
    .ZN(_053_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _175_ (
    .A1(_056_),
    .A2(\signal_gen.mix.n_val[2] ),
    .B1(_093_),
    .B2(\signal_gen.volN[1] ),
    .ZN(_095_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _176_ (
    .A1(_008_),
    .A2(_095_),
    .ZN(_054_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _177_ (
    .A1(_056_),
    .A2(\signal_gen.mix.n_val[3] ),
    .B1(_093_),
    .B2(\signal_gen.volN[2] ),
    .ZN(_096_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _178_ (
    .A1(_008_),
    .A2(_096_),
    .ZN(_013_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _179_ (
    .A1(\signal_gen.mix.n_val[4] ),
    .A2(_056_),
    .B1(_093_),
    .B2(\signal_gen.volN[3] ),
    .ZN(_097_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _180_ (
    .A1(_008_),
    .A2(_097_),
    .ZN(_014_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _181_ (
    .A1(\signal_gen.mix.started ),
    .A2(\signal_gen.mix.sum[1] ),
    .B(rst_n),
    .ZN(_098_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _182_ (
    .A1(\signal_gen.mix.started ),
    .A2(_059_),
    .B(_098_),
    .ZN(_016_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _183_ (
    .A1(\signal_gen.mix.started ),
    .A2(\signal_gen.mix.sum[2] ),
    .B(rst_n),
    .ZN(_099_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _184_ (
    .A1(\signal_gen.mix.started ),
    .A2(_058_),
    .B(_099_),
    .ZN(_017_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _185_ (
    .A1(\signal_gen.mix.started ),
    .A2(\signal_gen.mix.sum[3] ),
    .B(rst_n),
    .ZN(_100_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _186_ (
    .A1(\signal_gen.mix.started ),
    .A2(_057_),
    .B(_100_),
    .ZN(_018_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _187_ (
    .A1(\signal_gen.mix.sum[4] ),
    .A2(\signal_gen.mix.started ),
    .B(rst_n),
    .ZN(_101_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _188_ (
    .A1(_055_),
    .A2(\signal_gen.mix.started ),
    .B(_101_),
    .ZN(_019_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _189_ (
    .I0(\signal_gen.noise_gen.noise_reg[0] ),
    .I1(\signal_gen.noise_gen.feedback ),
    .S(\signal_gen.enableN ),
    .Z(_020_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _190_ (
    .I0(\signal_gen.mix.noise ),
    .I1(\signal_gen.noise_gen.noise_reg[0] ),
    .S(\signal_gen.enableN ),
    .Z(_021_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _191_ (
    .I0(\signal_gen.noise_gen.noise_reg[2] ),
    .I1(\signal_gen.mix.noise ),
    .S(\signal_gen.enableN ),
    .Z(_022_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _192_ (
    .I0(\signal_gen.noise_gen.noise_reg[3] ),
    .I1(\signal_gen.noise_gen.noise_reg[2] ),
    .S(\signal_gen.enableN ),
    .Z(_023_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _193_ (
    .I0(\signal_gen.noise_gen.noise_reg[4] ),
    .I1(\signal_gen.noise_gen.noise_reg[3] ),
    .S(\signal_gen.enableN ),
    .Z(_024_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _194_ (
    .I0(\signal_gen.noise_gen.noise_reg[5] ),
    .I1(\signal_gen.noise_gen.noise_reg[4] ),
    .S(\signal_gen.enableN ),
    .Z(_025_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _195_ (
    .I0(\signal_gen.noise_gen.noise_reg[6] ),
    .I1(\signal_gen.noise_gen.noise_reg[5] ),
    .S(\signal_gen.enableN ),
    .Z(_026_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _196_ (
    .I0(\signal_gen.noise_gen.noise_reg[7] ),
    .I1(\signal_gen.noise_gen.noise_reg[6] ),
    .S(\signal_gen.enableN ),
    .Z(_027_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _197_ (
    .I0(\signal_gen.noise_gen.noise_reg[8] ),
    .I1(\signal_gen.noise_gen.noise_reg[7] ),
    .S(\signal_gen.enableN ),
    .Z(_028_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _198_ (
    .I0(\signal_gen.noise_gen.noise_reg[9] ),
    .I1(\signal_gen.noise_gen.noise_reg[8] ),
    .S(\signal_gen.enableN ),
    .Z(_029_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _199_ (
    .I0(\signal_gen.noise_gen.noise_reg[10] ),
    .I1(\signal_gen.noise_gen.noise_reg[9] ),
    .S(\signal_gen.enableN ),
    .Z(_030_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _200_ (
    .I0(\signal_gen.noise_gen.noise_reg[11] ),
    .I1(\signal_gen.noise_gen.noise_reg[10] ),
    .S(\signal_gen.enableN ),
    .Z(_031_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _201_ (
    .I0(\signal_gen.noise_gen.noise_reg[12] ),
    .I1(\signal_gen.noise_gen.noise_reg[11] ),
    .S(\signal_gen.enableN ),
    .Z(_032_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _202_ (
    .I0(\signal_gen.noise_gen.noise_reg[13] ),
    .I1(\signal_gen.noise_gen.noise_reg[12] ),
    .S(\signal_gen.enableN ),
    .Z(_033_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _203_ (
    .A1(\signal_gen.enableN ),
    .A2(rst_n),
    .ZN(_102_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _204_ (
    .A1(\signal_gen.noise_gen.noise_reg[4] ),
    .A2(\signal_gen.noise_gen.noise_reg[13] ),
    .Z(_103_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _205_ (
    .A1(\signal_gen.noise_gen.feedback ),
    .A2(_102_),
    .ZN(_104_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _206_ (
    .A1(_102_),
    .A2(_103_),
    .B(_104_),
    .ZN(_034_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai22_1 _207_ (
    .A1(_064_),
    .A2(\signal_gen.pwmGen.clk_cnt[4] ),
    .B1(_065_),
    .B2(\signal_gen.pwmGen.clk_cnt[3] ),
    .ZN(_105_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _208_ (
    .A1(_063_),
    .A2(\signal_gen.pwmGen.clk_cnt[5] ),
    .B1(_064_),
    .B2(\signal_gen.pwmGen.clk_cnt[4] ),
    .ZN(_106_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _209_ (
    .A1(_063_),
    .A2(\signal_gen.pwmGen.clk_cnt[5] ),
    .ZN(_107_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi221_1 _210_ (
    .A1(_062_),
    .A2(\signal_gen.mix.mixout[6] ),
    .B1(_105_),
    .B2(_106_),
    .C(_107_),
    .ZN(_108_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _211_ (
    .A1(_062_),
    .A2(\signal_gen.mix.mixout[6] ),
    .B(rst_n),
    .ZN(_109_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _212_ (
    .A1(\signal_gen.pwmGen.clk_cnt[7] ),
    .A2(_108_),
    .A3(_109_),
    .ZN(_035_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _213_ (
    .A1(clk_scaled),
    .A2(_071_),
    .Z(_110_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _214_ (
    .A1(ena),
    .A2(_110_),
    .Z(_036_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _215_ (
    .I(rst_n),
    .ZN(_009_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _216_ (
    .I(rst_n),
    .ZN(_010_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _217_ (
    .I(rst_n),
    .ZN(_011_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _218_ (
    .I(rst_n),
    .ZN(_012_)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _219_ (
    .CLK(clk),
    .D(_000_),
    .Q(\clk_scaler.counter[0] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _220_ (
    .CLK(clk),
    .D(_001_),
    .Q(\clk_scaler.counter[1] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _221_ (
    .CLK(clk),
    .D(_002_),
    .Q(\clk_scaler.counter[2] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _222_ (
    .CLK(clk),
    .D(_003_),
    .Q(\clk_scaler.counter[3] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _223_ (
    .CLK(clk),
    .D(_004_),
    .Q(\clk_scaler.counter[4] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _224_ (
    .CLK(clk),
    .D(_005_),
    .Q(\clk_scaler.counter[5] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _225_ (
    .CLK(clk),
    .D(_006_),
    .Q(\clk_scaler.counter[6] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _226_ (
    .CLK(clk),
    .D(_007_),
    .Q(\clk_scaler.counter[7] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _227_ (
    .CLK(clk_scaled),
    .D(_041_),
    .Q(\signal_gen.mix.mixout[3] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _228_ (
    .CLK(clk_scaled),
    .D(_042_),
    .Q(\signal_gen.mix.mixout[4] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _229_ (
    .CLK(clk_scaled),
    .D(_043_),
    .Q(\signal_gen.mix.mixout[5] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _230_ (
    .CLK(clk_scaled),
    .D(_044_),
    .Q(\signal_gen.mix.mixout[6] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _231_ (
    .CLK(clk_scaled),
    .D(_045_),
    .Q(\signal_gen.pwmGen.clk_cnt[0] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _232_ (
    .CLK(clk_scaled),
    .D(_046_),
    .Q(\signal_gen.pwmGen.clk_cnt[1] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _233_ (
    .CLK(clk_scaled),
    .D(_047_),
    .Q(\signal_gen.pwmGen.clk_cnt[2] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _234_ (
    .CLK(clk_scaled),
    .D(_048_),
    .Q(\signal_gen.pwmGen.clk_cnt[3] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _235_ (
    .CLK(clk_scaled),
    .D(_049_),
    .Q(\signal_gen.pwmGen.clk_cnt[4] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _236_ (
    .CLK(clk_scaled),
    .D(_050_),
    .Q(\signal_gen.pwmGen.clk_cnt[5] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _237_ (
    .CLK(clk_scaled),
    .D(_051_),
    .Q(\signal_gen.pwmGen.clk_cnt[6] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _238_ (
    .CLK(clk_scaled),
    .D(_052_),
    .Q(\signal_gen.pwmGen.clk_cnt[7] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _239_ (
    .CLK(clk_scaled),
    .D(_053_),
    .Q(\signal_gen.mix.n_val[1] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _240_ (
    .CLK(clk_scaled),
    .D(_054_),
    .Q(\signal_gen.mix.n_val[2] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _241_ (
    .CLK(clk_scaled),
    .D(_013_),
    .Q(\signal_gen.mix.n_val[3] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _242_ (
    .CLK(clk_scaled),
    .D(_014_),
    .Q(\signal_gen.mix.n_val[4] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffsnq_1 _243_ (
    .CLK(clk_scaled),
    .D(_015_),
    .Q(\signal_gen.enableN ),
    .SETN(_008_)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _244_ (
    .CLK(clk_scaled),
    .D(_016_),
    .Q(\signal_gen.mix.sum[1] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _245_ (
    .CLK(clk_scaled),
    .D(_017_),
    .Q(\signal_gen.mix.sum[2] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _246_ (
    .CLK(clk_scaled),
    .D(_018_),
    .Q(\signal_gen.mix.sum[3] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _247_ (
    .CLK(clk_scaled),
    .D(_019_),
    .Q(\signal_gen.mix.sum[4] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _248_ (
    .CLK(clk_scaled),
    .D(rst_n),
    .Q(\signal_gen.mix.started )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffsnq_1 _249_ (
    .CLK(clk_scaled),
    .D(_020_),
    .Q(\signal_gen.noise_gen.noise_reg[0] ),
    .SETN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _250_ (
    .CLK(clk_scaled),
    .D(_021_),
    .Q(\signal_gen.mix.noise ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _251_ (
    .CLK(clk_scaled),
    .D(_022_),
    .Q(\signal_gen.noise_gen.noise_reg[2] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _252_ (
    .CLK(clk_scaled),
    .D(_023_),
    .Q(\signal_gen.noise_gen.noise_reg[3] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _253_ (
    .CLK(clk_scaled),
    .D(_024_),
    .Q(\signal_gen.noise_gen.noise_reg[4] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffsnq_1 _254_ (
    .CLK(clk_scaled),
    .D(_025_),
    .Q(\signal_gen.noise_gen.noise_reg[5] ),
    .SETN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffsnq_1 _255_ (
    .CLK(clk_scaled),
    .D(_026_),
    .Q(\signal_gen.noise_gen.noise_reg[6] ),
    .SETN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffsnq_1 _256_ (
    .CLK(clk_scaled),
    .D(_027_),
    .Q(\signal_gen.noise_gen.noise_reg[7] ),
    .SETN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _257_ (
    .CLK(clk_scaled),
    .D(_028_),
    .Q(\signal_gen.noise_gen.noise_reg[8] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _258_ (
    .CLK(clk_scaled),
    .D(_029_),
    .Q(\signal_gen.noise_gen.noise_reg[9] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffsnq_1 _259_ (
    .CLK(clk_scaled),
    .D(_030_),
    .Q(\signal_gen.noise_gen.noise_reg[10] ),
    .SETN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffsnq_1 _260_ (
    .CLK(clk_scaled),
    .D(_031_),
    .Q(\signal_gen.noise_gen.noise_reg[11] ),
    .SETN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _261_ (
    .CLK(clk_scaled),
    .D(_032_),
    .Q(\signal_gen.noise_gen.noise_reg[12] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffsnq_1 _262_ (
    .CLK(clk_scaled),
    .D(_033_),
    .Q(\signal_gen.noise_gen.noise_reg[13] ),
    .SETN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _263_ (
    .CLK(clk_scaled),
    .D(_034_),
    .Q(\signal_gen.noise_gen.feedback )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _264_ (
    .CLK(clk_scaled),
    .D(_035_),
    .Q(signal_bit_out)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _265_ (
    .CLK(clk),
    .D(_036_),
    .Q(clk_scaled),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffsnq_1 _266_ (
    .CLK(clk_scaled),
    .D(_037_),
    .Q(\signal_gen.volN[0] ),
    .SETN(_009_)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffsnq_1 _267_ (
    .CLK(clk_scaled),
    .D(_038_),
    .Q(\signal_gen.volN[1] ),
    .SETN(_010_)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _268_ (
    .CLK(clk_scaled),
    .D(_039_),
    .Q(\signal_gen.volN[2] ),
    .RN(_011_)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _269_ (
    .CLK(clk_scaled),
    .D(_040_),
    .Q(\signal_gen.volN[3] ),
    .RN(_012_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _270_ (
    .ZN(_007_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _271_ (
    .ZN(_006_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _272_ (
    .ZN(_005_)
  );
endmodule
