/* Generated by Yosys 0.57 (git sha1 3aca86049, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

module tt_um_felixfeierabend(ui_in, uo_out, uio_in, uio_out, uio_oe, ena, clk, rst_n);
  input [7:0] ui_in;
  wire [7:0] ui_in;
  output [7:0] uo_out;
  wire [7:0] uo_out;
  input [7:0] uio_in;
  wire [7:0] uio_in;
  output [7:0] uio_out;
  wire [7:0] uio_out;
  output [7:0] uio_oe;
  wire [7:0] uio_oe;
  input ena;
  wire ena;
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  gf180mcu_fd_sc_mcu7t5v0__tieh _00_ (
    .Z(uio_oe[0])
  );
  gf180mcu_fd_sc_mcu7t5v0__tieh _01_ (
    .Z(uio_oe[1])
  );
  gf180mcu_fd_sc_mcu7t5v0__tieh _02_ (
    .Z(uio_oe[2])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _03_ (
    .ZN(uio_oe[3])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _04_ (
    .ZN(uio_oe[4])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _05_ (
    .ZN(uio_oe[5])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _06_ (
    .ZN(uio_oe[6])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _07_ (
    .ZN(uio_oe[7])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _08_ (
    .ZN(uio_out[0])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _09_ (
    .ZN(uio_out[1])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _10_ (
    .ZN(uio_out[2])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _11_ (
    .ZN(uio_out[3])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _12_ (
    .ZN(uio_out[4])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _13_ (
    .ZN(uio_out[5])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _14_ (
    .ZN(uio_out[6])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _15_ (
    .ZN(uio_out[7])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _16_ (
    .ZN(uo_out[0])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _17_ (
    .ZN(uo_out[1])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _18_ (
    .ZN(uo_out[2])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _19_ (
    .ZN(uo_out[3])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _20_ (
    .ZN(uo_out[4])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _21_ (
    .ZN(uo_out[5])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _22_ (
    .ZN(uo_out[6])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _23_ (
    .ZN(uo_out[7])
  );
endmodule
